// Generated by tools/Invoke-CatalogCompile.ps1 from globalization/catalogs.
// Edit the source catalog and regenerate; changes made here are overwritten.
// locale: zh-CN  domain: pool

package catalog

// DatazhCNpool is the compiled catalog for this locale and domain. It is a
// string so the package carries no init cost until a caller decodes it.
const DatazhCNpool = `{
  "pool.a_pool_groups_hosts_under_a_stable_pool_id_guid_a_host_belongs_to": "池使用固定的池ID（GUID）将宿主机分组；每台宿主机最多属于一个池。池状态显示成员当前正在执行的操作，选择一个值会将其应用于所有成员。",
  "pool.a_pool_s_members_are_meant_to_be_configured_alike_to_copy_one_pee": [
    "* 池内成员应采用相同配置。要将一个对等成员的配置复制到另一台宿主机，请在目标宿主机上运行：",
    {
      "arg": "command1",
      "type": "token",
      "trust": "internal"
    }
  ],
  "pool.a_scan_of_value1_is_already_running_following_that_one": [
    "对",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "的扫描已在运行；正在跟踪该扫描。"
  ],
  "pool.a_test_set_is_a_framework_project_repo_pair_gh_token_is_not_store": "测试集由框架和项目仓库配对组成。GH_TOKEN不存储在此处，而是保留在各宿主机本地的test.config.yml / 保管库中。",
  "pool.actions": "操作",
  "pool.add_host_failed_value1": [
    "添加宿主机失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.added_value1": [
    "已添加",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "。"
  ],
  "pool.added_value1_to_value2": [
    "已将",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "添加到",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.address": "地址",
  "pool.aggregator_unavailable_value1_control_state_is_unknown_moving_hos": [
    "聚合器不可用（",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "）；控制状态未知。仍可移动宿主机。"
  ],
  "pool.aggregator_url": "聚合器URL",
  "pool.all_checks_passed_pool_control_service_value1_value2_collected_va": [
    "所有检查均已通过。pool-control-service ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "（",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "），采集时间：",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.apply_value1_to_all_value2_host_s_in_pool_value3": [
    "将“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”应用于池",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "中的全部",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "台宿主机？"
  ],
  "pool.asks_every_address_in_the_network_for_a_yuruna_host_status_servic": "向网络中的每个地址查询Yuruna宿主机status service，并将有响应的宿主机\n      添加到监控列表，无论其是否属于池、是否已登记。\n      扫描不会更改宿主机本身。",
  "pool.assign": "分配",
  "pool.assign_failed_value1": [
    "分配失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.assign_test_set": "分配测试集？",
  "pool.assign_test_set_50fb7bbc": "分配测试集",
  "pool.assign_test_sets_to_pools": "将测试集分配给池",
  "pool.assign_value1_to_value2": [
    "将“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”分配给",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "？"
  ],
  "pool.assign_yuruna_pool_control": "分配——Yuruna池控制",
  "pool.assigned_value1_to_pool_value2": [
    "已将“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”分配给池“",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "”。"
  ],
  "pool.board": "看板",
  "pool.board_yuruna_pool_control": "看板——Yuruna池控制",
  "pool.cancel": "取消",
  "pool.change_test_set": "更改测试集……",
  "pool.check": "检查",
  "pool.choose_a_test_set": "（选择测试集）",
  "pool.command1_scans_command2_through_command3_a_smaller_prefix_number_": [
    {
      "arg": "command1",
      "type": "token",
      "trust": "internal"
    },
    "扫描从",
    {
      "arg": "command2",
      "type": "token",
      "trust": "internal"
    },
    "到",
    {
      "arg": "command3",
      "type": "token",
      "trust": "internal"
    },
    "的地址；前缀数字越小，覆盖的地址越多（",
    {
      "arg": "command4",
      "type": "token",
      "trust": "internal"
    },
    "为65,536个），越大则越少（",
    {
      "arg": "command5",
      "type": "token",
      "trust": "internal"
    },
    "为一台机器）。使用网络内的地址表示同一子网：",
    {
      "arg": "command6",
      "type": "token",
      "trust": "internal"
    },
    "等同于",
    {
      "arg": "command7",
      "type": "token",
      "trust": "internal"
    },
    "。"
  ],
  "pool.continue": "继续",
  "pool.control": "控制",
  "pool.cores": "核心数",
  "pool.could_not_assign_value1": [
    "无法分配：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.could_not_collect_diagnostics_value1": [
    "无法收集诊断信息：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.could_not_forget_that_host_value1": [
    "无法移除该宿主机的记录：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.could_not_load_pool_intent_value1": [
    "无法加载池的预期配置：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.could_not_load_pools_value1": [
    "无法加载池：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.could_not_load_test_sets_value1": [
    "无法加载测试集：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.could_not_load_the_board_value1_retrying_on_the_next_refresh": [
    "无法加载看板：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "。将在下次刷新时重试。"
  ],
  "pool.could_not_read_the_scan_status_value1": [
    "无法读取扫描状态：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.create_failed_value1": [
    "创建失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.create_pool": "创建池",
  "pool.created_pool_value1": [
    "已创建池“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”。"
  ],
  "pool.cycles": "周期",
  "pool.delete": "删除",
  "pool.delete_failed_value1": [
    "删除失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.delete_pool": "删除池",
  "pool.delete_pool_value1": [
    "删除池",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.delete_pool_value1_this_cannot_be_undone": [
    "删除池“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”后无法撤销。确认删除吗？"
  ],
  "pool.delete_test_set_value1": [
    "删除测试集",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.delete_test_set_value1_this_cannot_be_undone": [
    "删除测试集“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”后无法撤销。确认删除吗？"
  ],
  "pool.deleted_pool_value1": [
    "已删除池“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”。"
  ],
  "pool.deleted_value1": [
    "已删除“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”。"
  ],
  "pool.detail": "详情",
  "pool.diagnostic_auto_enrollment_assignment": "宿主机自动加入此处，并继续运行各自的项目。",
  "pool.diagnostic_configure_repo": "传入--repo-dir，使其指向yuruna框架的检出目录。",
  "pool.diagnostic_git_not_found": [
    "在PATH中未找到：",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.diagnostic_install_git": "pool-admin命令行工具会克隆和推送池意图；请在客户机中安装git。",
  "pool.diagnostic_install_pwsh": "在客户机中安装PowerShell。packages.microsoft.com未提供适用于此Ubuntu版本的powershell软件包；请使用GitHub发行版中的tar归档包，然后重启pool-control-service.service。",
  "pool.diagnostic_intent_absent": "没有可检查的意图URL",
  "pool.diagnostic_intent_configure": "客户机初始化时，若池NAS上没有可写存储库，则会创建一个；此处为空表示初始化时未挂载NAS。请在/etc/yuruna/pool-control-service.env中设置POOL_CONTROL_INTENT_GIT_URL（每次请求时重新读取，无需重启），或在重新构建前设置test/test.config.yml中的pool.intentGitUrl。",
  "pool.diagnostic_intent_empty": "为空：未从启动参数或配置文件中解析出意图存储库",
  "pool.diagnostic_intent_initialize": "池NAS存储库在客户机初始化时创建；若NAS挂载较晚，请重新运行初始化脚本，或对该存储库执行git init --bare。",
  "pool.diagnostic_intent_not_bare": [
    {
      "arg": "path",
      "type": "detail",
      "trust": "external"
    },
    "：不是git裸仓库（",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    },
    "）"
  ],
  "pool.diagnostic_intent_not_writable": [
    {
      "arg": "path",
      "type": "detail",
      "trust": "external"
    },
    "：裸仓库存在，但不可写：",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.diagnostic_intent_override": [
    "  （配置文件覆盖启动参数",
    {
      "arg": "flag",
      "type": "detail",
      "trust": "external"
    },
    "）"
  ],
  "pool.diagnostic_intent_permission": "写入会在推送时失败。请检查池NAS挂载的uid/gid是否与服务用户匹配。",
  "pool.diagnostic_intent_pull_only": "除非服务器运行git-http-backend，否则http(s)意图存储库仅支持拉取：读取可正常进行，但所有写入都会在推送时失败。可写存储库是池NAS上的裸仓库。",
  "pool.diagnostic_intent_remote": "远程URL；可达性由intent-read检查",
  "pool.diagnostic_intent_writable": [
    {
      "arg": "path",
      "type": "detail",
      "trust": "external"
    },
    "：裸仓库，可写"
  ],
  "pool.diagnostic_no_output": "无输出",
  "pool.diagnostic_not_configured": "未配置",
  "pool.diagnostic_persistence_configure": "传入Options.Store时一并传入Options.StateDir，以便此检查探测实际路径。",
  "pool.diagnostic_persistence_disabled": "持久化已禁用（未配置状态目录）",
  "pool.diagnostic_persistence_logs_missing": "审计日志和status.json未写入；此目录由池NAS挂载提供。",
  "pool.diagnostic_persistence_nas_missing": "池NAS未挂载；审计日志无法持久保存。",
  "pool.diagnostic_persistence_permission": "检查挂载的uid/gid选项是否与服务用户匹配。",
  "pool.diagnostic_persistence_unknown": "存储已启用，但未向服务器报告状态目录",
  "pool.diagnostic_pwsh_execution": [
    "pwsh存在于",
    {
      "arg": "path",
      "type": "detail",
      "trust": "external"
    },
    "，但未能运行；请检查其共享库依赖项。"
  ],
  "pool.diagnostic_pwsh_not_found": [
    "未找到：",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.diagnostic_raw_invocation": "查看下方的原始调用，了解命令行工具自身的输出；上方的检查会指出缺失的依赖项。",
  "pool.diagnostic_repo_complete": [
    {
      "arg": "path",
      "type": "detail",
      "trust": "external"
    },
    "：全部",
    {
      "arg": "count",
      "type": "detail",
      "trust": "external"
    },
    "个pool-admin命令行工具均存在"
  ],
  "pool.diagnostic_repo_missing": "框架检出副本缺失；请重新运行客户机初始化脚本。",
  "pool.diagnostic_repo_missing_files": [
    {
      "arg": "path",
      "type": "detail",
      "trust": "external"
    },
    "：缺少",
    {
      "arg": "files",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.diagnostic_repo_partial": "检出副本已过时或不完整；请重新获取框架归档包。",
  "pool.diagnostic_revision_archive": [
    {
      "arg": "revision",
      "type": "detail",
      "trust": "external"
    },
    "（",
    {
      "arg": "file",
      "type": "detail",
      "trust": "external"
    },
    "，仅由归档包生成的检出副本）"
  ],
  "pool.diagnostic_revision_conflict": [
    "git报告的版本为",
    {
      "arg": "git",
      "type": "detail",
      "trust": "external"
    },
    "，但",
    {
      "arg": "file",
      "type": "detail",
      "trust": "external"
    },
    "记录的是",
    {
      "arg": "sidecar",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.diagnostic_revision_corrupt": "修订版本附属文件已损坏，无法验证已部署的提交。请从status service重新获取框架归档包，然后重启pool-control-service.service。",
  "pool.diagnostic_revision_git": [
    {
      "arg": "revision",
      "type": "detail",
      "trust": "external"
    },
    "（Git检出副本）"
  ],
  "pool.diagnostic_revision_missing": "检出副本中没有任何内容标明提交，因此无法将此部署关联到已审核的源代码。请从status service重新获取框架归档包，然后重启pool-control-service.service。",
  "pool.diagnostic_revision_mixed": "检出副本与其修订版本附属文件指向不同的提交；目录树混合了不同来源的内容。请从status service重新获取框架归档包，然后重启pool-control-service.service。",
  "pool.diagnostic_revision_no_source": [
    "没有Git检出副本，也没有",
    {
      "arg": "file",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.diagnostic_state_not_writable": [
    {
      "arg": "path",
      "type": "detail",
      "trust": "external"
    },
    "：不可写：",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.diagnostic_state_writable": [
    {
      "arg": "path",
      "type": "detail",
      "trust": "external"
    },
    "：可写"
  ],
  "pool.diagnostics": "诊断",
  "pool.diagnostics_yuruna_pool_control": "诊断 — Yuruna Pool Control",
  "pool.discovered": "已发现",
  "pool.discovered_hosts_are_not_being_saved_value1": [
    "发现的宿主机未保存：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.display_name": "显示名称",
  "pool.duration": "持续时间",
  "pool.each_of_the_four_numbers_must_be_0_to_255": "四个数字中的每个数字都必须在0到255之间。",
  "pool.each_pool_tests_one_test_set_a_framework_project_repo_pair_gh_tok": "每个池测试一个测试集（一个框架仓库与一个项目仓库的组合）。\n      GH_TOKEN保留在宿主机本地，绝不存储在池意图中。",
  "pool.edit": "编辑",
  "pool.empty": "（空）",
  "pool.enrollment_target": [
    {
      "arg": "pool",
      "type": "detail",
      "trust": "external"
    },
    " -- 自动注册目标"
  ],
  "pool.enter_a_network_for_example_value1": [
    "输入网络，例如",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "。"
  ],
  "pool.enter_a_pool_id": "输入池ID。",
  "pool.enter_the_lab_token": "输入实验室令牌",
  "pool.every_dependency_a_ui_request_touches_probed_in_the_order_a_reque": "按界面请求访问依赖项的顺序，逐一探测所有依赖项。失败的检查会指出客户机中需要修复的内容。",
  "pool.every_host_the_aggregator_knows_control_command1_this_lab_s_token": [
    "聚合器已知的所有宿主机。控制状态：",
    {
      "arg": "command1",
      "type": "token",
      "trust": "internal"
    },
    "（持有本实验室的令牌，时钟一致——仅此类宿主机会自动注册）、",
    {
      "arg": "command2",
      "type": "token",
      "trust": "internal"
    },
    "（令牌不同）、",
    {
      "arg": "command3",
      "type": "token",
      "trust": "internal"
    },
    "（时钟异常）、",
    {
      "arg": "command4",
      "type": "token",
      "trust": "internal"
    },
    "（从未注册）。选择池会将宿主机移入该池，每台宿主机最多属于一个池。框架和项目是宿主机报告的仓库，链接指向其源代码；",
    {
      "arg": "command5",
      "type": "token",
      "trust": "internal"
    },
    "表示无法读取配置的仓库。标记为已更换密钥的行表示某台机器的旧身份：该机器已重新安装镜像或重新克隆，因此当前宿主机使用旁边显示的ID响应，而池成员关系仍保留在旧身份上；请从该行移交。解锁此浏览器后将显示宿主机名称。"
  ],
  "pool.exit_code": "退出代码",
  "pool.fail": "失败",
  "pool.failed": "失败",
  "pool.first_seen": "首次发现",
  "pool.forget": "移除记录",
  "pool.found": "已发现",
  "pool.found_and_added": "已发现并添加",
  "pool.found_by_a_network_scan_value1": [
    "通过网络扫描发现",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.found_by_scanning_the_network_it_belongs_to_no_pool_and_has_not_r": "通过网络扫描发现；不属于任何池，且尚未向聚合器注册。",
  "pool.framework": "框架",
  "pool.framework_project": "框架 / 项目",
  "pool.framework_revision": "框架修订版本",
  "pool.framework_url": "框架URL",
  "pool.framework_version": "框架版本",
  "pool.free_storage": "可用存储空间",
  "pool.go": "Go运行时",
  "pool.guide": "指南",
  "pool.hand_over": "移交",
  "pool.hand_over_failed_value1": [
    "移交失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.holds_a_different_token_re_enroll_against_this_proxy": "持有不同的令牌；请通过此代理重新注册。",
  "pool.holds_this_lab_s_token_clock_agrees": "持有本实验室的令牌；时钟一致。",
  "pool.home": "主目录（HOME）",
  "pool.host": "+ 宿主机",
  "pool.host_id": "宿主机ID",
  "pool.host_id_7b624c8f": "宿主机ID",
  "pool.host_id_to_add_to_pool_value1": [
    "要添加到池",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "的宿主机ID"
  ],
  "pool.host_refresh_body_invalid": [
    "刷新请求必须为JSON对象，值均为字符串，且仅包含hostId、requestId、tier和maxRung（",
    {
      "arg": "detail",
      "type": "identifier",
      "trust": "internal"
    },
    "）。"
  ],
  "pool.host_refresh_busy": [
    "宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "正在处理刷新请求",
    {
      "arg": "activeRequestId",
      "type": "identifier",
      "trust": "external"
    },
    "；请跟踪该请求，不要启动新请求。"
  ],
  "pool.host_refresh_control_proof_unavailable": [
    "无法获取宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "的控制凭证（",
    {
      "arg": "detail",
      "type": "identifier",
      "trust": "internal"
    },
    "）。"
  ],
  "pool.host_refresh_field_unsupported": [
    "刷新请求包含不支持的字段",
    {
      "arg": "field",
      "type": "identifier",
      "trust": "external"
    },
    "；远程请求一律不接受强制和硬停止选项。"
  ],
  "pool.host_refresh_host_address_unknown": [
    "池聚合器已知宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "，但没有其地址。"
  ],
  "pool.host_refresh_host_id_invalid": "hostId必须是由32个十六进制字符组成的宿主机ID。",
  "pool.host_refresh_host_refused": [
    "宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "拒绝了刷新（HTTP ",
    {
      "arg": "status",
      "type": "integer",
      "trust": "external"
    },
    "，",
    {
      "arg": "hostReason",
      "type": "identifier",
      "trust": "external"
    },
    "）。"
  ],
  "pool.host_refresh_host_unavailable": [
    "宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "无法启动刷新（HTTP ",
    {
      "arg": "status",
      "type": "integer",
      "trust": "external"
    },
    "，",
    {
      "arg": "hostReason",
      "type": "identifier",
      "trust": "external"
    },
    "）；请使用相同的请求ID ",
    {
      "arg": "requestId",
      "type": "identifier",
      "trust": "external"
    },
    "重试。"
  ],
  "pool.host_refresh_host_unknown": [
    "池聚合器未知宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "。"
  ],
  "pool.host_refresh_host_unreachable": [
    "宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "未响应；请使用相同的请求ID ",
    {
      "arg": "requestId",
      "type": "identifier",
      "trust": "external"
    },
    "重试。"
  ],
  "pool.host_refresh_mint_failed": [
    "此服务无法为宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "的刷新请求签名。"
  ],
  "pool.host_refresh_reply_invalid": [
    "宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "返回了本服务无法使用的响应（",
    {
      "arg": "detail",
      "type": "identifier",
      "trust": "internal"
    },
    "）。"
  ],
  "pool.host_refresh_request_closed": [
    "宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "上的请求",
    {
      "arg": "requestId",
      "type": "identifier",
      "trust": "external"
    },
    "已结束（",
    {
      "arg": "state",
      "type": "identifier",
      "trust": "external"
    },
    "，",
    {
      "arg": "verdict",
      "type": "identifier",
      "trust": "external"
    },
    "）；请生成新的请求标识符以再次刷新。"
  ],
  "pool.host_refresh_request_conflict": [
    "请求",
    {
      "arg": "requestId",
      "type": "identifier",
      "trust": "external"
    },
    "已用于不同的层级或上限；请重新发送原始策略或生成新的请求标识符。"
  ],
  "pool.host_refresh_request_id_invalid": "requestId必须是小写UUID（8-4-4-4-12），由调用方生成一次，并在每次重试时复用。",
  "pool.host_refresh_rung_unsupported": "maxRung必须为probe、reclaim、start-if-stopped、restart-if-hung或restart-broker。",
  "pool.host_refresh_signing_unconfigured": [
    "远程宿主机刷新已禁用：本服务未持有刷新签名授权（",
    {
      "arg": "path",
      "type": "detail",
      "trust": "internal"
    },
    "）。"
  ],
  "pool.host_refresh_tier_unsupported": "远程只能请求restart层级；full层级仅限本地使用。",
  "pool.host_refresh_unavailable": [
    "宿主机",
    {
      "arg": "hostId",
      "type": "identifier",
      "trust": "external"
    },
    "未公布远程刷新能力（",
    {
      "arg": "reason",
      "type": "identifier",
      "trust": "external"
    },
    "）。"
  ],
  "pool.host_value1_no_longer_answers_at_value2_value3_does_move_the_pool": [
    "宿主机",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "不再在",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "响应；现在由",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "响应。\n\n是否将池成员资格转移到该标识符，并忘记当前标识符？"
  ],
  "pool.hostid_42_30hex": "宿主机标识hostId（42+30hex）",
  "pool.hostname": "宿主机名",
  "pool.hosts": "宿主机",
  "pool.hosts_project_denied": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "台宿主机无法读取分配的项目。请为其令牌授予访问权限，或分配其他测试集。"
      ]
    }
  },
  "pool.hosts_reporting": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "台宿主机 - ",
        {
          "arg": "reporting",
          "type": "integer",
          "trust": "internal"
        },
        "台正在上报"
      ]
    }
  },
  "pool.hosts_switch_assigned": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "台宿主机将在下一个周期切换到分配的项目。"
      ]
    }
  },
  "pool.hosts_switch_project": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "台宿主机将在下一个周期切换到",
        {
          "arg": "project",
          "type": "detail",
          "trust": "external"
        },
        "。"
      ]
    }
  },
  "pool.hosts_yuruna_pool_control": "宿主机 — Yuruna Pool Control",
  "pool.intent_git_url": "意图git URL",
  "pool.intent_read_raw_invocation": "意图读取 — 原始调用",
  "pool.ips": "IP地址：",
  "pool.it_will_also_be_excluded_from_auto_enrollment_so_the_sweep_will_n": "\n\n它也将被排除在自动注册之外，因此扫描不会将其重新添加。",
  "pool.lab_token": "实验室令牌",
  "pool.label_1h": "时长：1h",
  "pool.label_24h": "时长：24h",
  "pool.label_30d": "时长：30d",
  "pool.label_7d": "时长：7d",
  "pool.last_seen": "最后发现时间",
  "pool.last_seen_value1": [
    "，最后发现时间为",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.listen_addr": "监听地址",
  "pool.live_numbers_unavailable_value1_assigning_still_works": [
    "实时数据不可用（",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "）。仍可进行分配。"
  ],
  "pool.loaded": "已加载：",
  "pool.loading_hosts": "正在加载宿主机……",
  "pool.loading_pools": "正在加载池……",
  "pool.loading_test_sets": "正在加载测试集……",
  "pool.lowercase_dns_safe": "小写，符合DNS命名规则",
  "pool.members": "成员 *",
  "pool.members_1044a4c0": "成员",
  "pool.memory": "内存",
  "pool.menu": "菜单",
  "pool.mixed": "混合",
  "pool.monitored_by_discovery": "由发现功能监控",
  "pool.move_failed_value1": [
    "移动失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.move_host_value1_to_value2_value3": [
    "是否将宿主机",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "移至",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "？",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.move_this_host_s_pool_membership_to_value1_the_id_that_answers_at": [
    "将此宿主机的池成员资格转移到在此地址响应的标识符",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "，并停止显示当前宿主机。"
  ],
  "pool.moved_to_value1": [
    "已移至",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "。"
  ],
  "pool.moves": "移动",
  "pool.name": "名称",
  "pool.name_frameworkurl_and_projecturl_are_all_required": "name、frameworkUrl和projectUrl均为必填项。",
  "pool.network": "网络",
  "pool.never_enrolled_a_lab_token_run_set_labtoken_ps1_on_the_host": "尚未注册过实验室令牌，请在宿主机上运行Set-LabToken.ps1。",
  "pool.no_hosts_discovered_yet": "尚未发现宿主机。",
  "pool.no_id_reported": "（未上报标识符）",
  "pool.no_pools_defined_create_one_on_the_pools_page": "尚未定义池。请在“池”页面创建一个。",
  "pool.no_pools_yet": "暂无池。",
  "pool.no_pools_yet_create_one_from_menu_pools": "暂无池。请通过“菜单 → 池”创建一个。",
  "pool.no_scan_has_run_yet": "尚未运行过扫描。",
  "pool.no_test_sets_yet": "暂无测试集。",
  "pool.none": "（无）",
  "pool.not": "不",
  "pool.not_answered_yet_or_the_proxy_holds_no_token_of_its_own": "尚未响应，或代理未持有自己的令牌。",
  "pool.not_cidr_notation_write_an_address_a_slash_and_a_prefix_length_19": "不是CIDR表示法。请输入地址、斜杠和前缀长度：192.168.7.0/24.",
  "pool.nothing_new_every_yuruna_host_in_that_range_was_already_monitored": "没有新增宿主机。该范围内的所有Yuruna宿主机均已受到监控。",
  "pool.nothing_to_move_the_live_id_already_has_the_pool_it_should": "无需移动：当前响应的标识符已归属正确的池。",
  "pool.only_hosts_this_scan_added_a_yuruna_host_that_was_already_monitor": "仅列出本次扫描添加的宿主机。已受到监控的Yuruna宿主机已计入上方统计，不再重复列出。",
  "pool.open_this_host_s_own_status_page_at_value1_found_by_a_network_sca": [
    "打开此宿主机在",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "的自身状态页面（通过网络扫描",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "发现）"
  ],
  "pool.optional": "可选",
  "pool.own_network": "本服务自身的网络",
  "pool.pages": "页面",
  "pool.pass": "通过",
  "pool.path": "路径（PATH）",
  "pool.pause": "暂停",
  "pool.pause_after_cycle": "周期结束后暂停",
  "pool.pause_after_step": "步骤结束后暂停",
  "pool.paused_after_cycle_and_step": "已在周期和步骤结束后暂停",
  "pool.persisted_health": "已持久化的健康状态",
  "pool.persistence_disabled": "（持久化已禁用）",
  "pool.pick_a_test_set_first_define_one_on_the_test_sets_page": "请先选择测试集（在“测试集”页面定义一个）。",
  "pool.pid": "进程标识（pid）",
  "pool.platform": "平台",
  "pool.pool": "池",
  "pool.pool_for_host_value1": [
    "宿主机",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "所属的池"
  ],
  "pool.pool_id": "池ID",
  "pool.pool_id_66d3d3f3": "池标识符",
  "pool.pool_membership_moved_to_value1": [
    "池成员资格已转移到",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "。"
  ],
  "pool.pool_project_denied": "池为此宿主机分配了其git凭据无法读取的项目。请为其令牌授予该仓库的访问权限，或为池重新分配所有成员都能读取的项目。在此之前，该宿主机的周期将持续失败，重试无法解决此问题。",
  "pool.pool_project_unreachable": "此宿主机所属池分配的项目未响应。这是网络问题，而非权限问题，克隆操作将按正常退避策略重试。",
  "pool.pool_status": "池状态",
  "pool.pool_status_change_failed_value1": [
    "池状态更改失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.pool_status_for_value1": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "的池状态"
  ],
  "pool.pool_value1_has_members_remove_them_first": [
    "池“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”中有成员；请先移除成员。"
  ],
  "pool.pool_value1_has_no_members_nothing_to_drive": [
    "池“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”中没有成员；无可驱动的对象。"
  ],
  "pool.pools": "池",
  "pool.pools_yuruna_pool_control": "池 — Yuruna Pool Control",
  "pool.process": "进程",
  "pool.progress": "进度",
  "pool.project": "项目",
  "pool.project_url": "项目URL",
  "pool.pwsh_pwsh_flag": "pwsh（--pwsh标志）",
  "pool.pwsh_resolved": "pwsh（已解析）",
  "pool.re_keyed": "已更换密钥",
  "pool.re_run_checks": "重新运行检查",
  "pool.refresh": "刷新",
  "pool.remove_failed_value1": [
    "移除失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.remove_host_failed_value1": [
    "移除宿主机失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.remove_host_value1_from_pool_value2": [
    "从池",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "中移除宿主机",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.remove_host_value1_from_pool_value2_this_cannot_be_undone": [
    "从池",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "中移除宿主机",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "后无法撤销。是否移除？"
  ],
  "pool.repo_denied_detail": {
    "kind": "select",
    "selector": "repo",
    "variants": {
      "framework": "此宿主机无法读取为其配置的框架仓库。请检查其git凭据和test.config.yml中的url。",
      "other": "此宿主机无法读取为其配置的仓库。请检查其git凭据和test.config.yml中的url。",
      "project": "此宿主机无法读取为其配置的项目仓库。请检查其git凭据和test.config.yml中的url。"
    }
  },
  "pool.repo_dir": "仓库目录",
  "pool.repo_held_detail": {
    "kind": "select",
    "selector": "repo",
    "variants": {
      "framework": "此宿主机实际持有的框架仓库。",
      "other": "此宿主机实际持有的仓库。",
      "project": "此宿主机实际持有的项目仓库。"
    }
  },
  "pool.repo_no_access": "无访问权限",
  "pool.repo_unconfigured_detail": {
    "kind": "select",
    "selector": "repo",
    "variants": {
      "framework": "此宿主机既没有框架仓库，也未配置框架仓库，或者尚未响应。",
      "other": "此宿主机既没有仓库，也未配置仓库，或者尚未响应。",
      "project": "此宿主机既没有项目仓库，也未配置项目仓库，或者尚未响应。"
    }
  },
  "pool.result": "结果",
  "pool.row_number": "行号",
  "pool.run": "运行",
  "pool.running": "正在运行：",
  "pool.running_checks": "正在运行检查……",
  "pool.runtime_environment": "运行时环境",
  "pool.save_failed_value1": [
    "保存失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.save_test_set": "保存测试集",
  "pool.saved_test_set_value1": [
    "已保存测试集“",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "”。"
  ],
  "pool.scan": "扫描",
  "pool.scan_a_network_for_yuruna_hosts": "扫描网络以查找Yuruna宿主机",
  "pool.scan_count": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        "扫描",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "个地址。"
      ]
    }
  },
  "pool.scan_finished": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        "对",
        {
          "arg": "network",
          "type": "detail",
          "trust": "external"
        },
        "的",
        {
          "arg": "kind",
          "type": "detail",
          "trust": "external"
        },
        "已于",
        {
          "arg": "time",
          "type": "detail",
          "trust": "external"
        },
        "完成：已探测",
        {
          "arg": "done",
          "type": "detail",
          "trust": "external"
        },
        "/",
        {
          "arg": "total",
          "type": "detail",
          "trust": "external"
        },
        "个地址，已添加",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "台宿主机，另有",
        {
          "arg": "monitored",
          "type": "detail",
          "trust": "external"
        },
        "台已受监控。",
        {
          "arg": "detail",
          "type": "detail",
          "trust": "external"
        }
      ]
    }
  },
  "pool.scan_label": "扫描",
  "pool.scan_limit": [
    "/",
    {
      "arg": "prefix",
      "type": "detail",
      "trust": "external"
    },
    "涵盖",
    {
      "arg": "count",
      "type": "integer",
      "trust": "internal"
    },
    "个地址；此服务最多扫描",
    {
      "arg": "limit",
      "type": "detail",
      "trust": "external"
    },
    "个地址。请使用更小的网络范围（更大的前缀长度）。"
  ],
  "pool.scan_refused_value1": [
    "扫描被拒绝：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.scan_yuruna_pool_control": "扫描 — Yuruna Pool Control",
  "pool.service_diagnostics": "服务诊断",
  "pool.service_user": "服务用户",
  "pool.show_hostnames": "显示宿主机名称",
  "pool.started_at": "启动时间",
  "pool.state": "状态",
  "pool.state_dir": "状态目录",
  "pool.state_fail": "失败",
  "pool.state_idle": "空闲",
  "pool.state_mismatch": "不匹配",
  "pool.state_none": "无",
  "pool.state_pass": "通过",
  "pool.state_paused": "已暂停",
  "pool.state_ready": "就绪",
  "pool.state_running": "运行中",
  "pool.state_skew": "偏差",
  "pool.state_stopped": "已停止",
  "pool.state_unknown": "未知",
  "pool.stdout": "标准输出（stdout）",
  "pool.stop_monitoring_value1_the_next_scan_of_that_network_will_find_it": [
    "是否停止监控",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "？\n\n如果它仍在该网络中，下次扫描该网络时会再次发现它。"
  ],
  "pool.success": "成功",
  "pool.sweep_label": "定期扫描",
  "pool.sweep_minutes": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        "每隔",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "分钟自动扫描一次",
        {
          "arg": "network",
          "type": "detail",
          "trust": "external"
        },
        "，查询端口",
        {
          "arg": "port",
          "type": "detail",
          "trust": "external"
        },
        "。"
      ]
    }
  },
  "pool.sweep_seconds": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        "每隔",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "秒自动扫描一次",
        {
          "arg": "network",
          "type": "detail",
          "trust": "external"
        },
        "，查询端口",
        {
          "arg": "port",
          "type": "detail",
          "trust": "external"
        },
        "。"
      ]
    }
  },
  "pool.test_set_for_pool_value1": [
    "池",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "的测试集"
  ],
  "pool.test_set_label": [
    {
      "arg": "name",
      "type": "text",
      "trust": "external"
    },
    "的测试集"
  ],
  "pool.test_sets": "测试集",
  "pool.test_sets_yuruna_pool_control": "测试集 — Yuruna Pool Control",
  "pool.the_6_character_code_on_the_yuruna_hosts_dashboard_s_lab_token_ti": "Yuruna宿主机仪表板“实验室令牌”磁贴上的6字符代码。刚读取的代码约三分钟内有效，无需匆忙输入。",
  "pool.the_exact_command_its_exit_code_and_both_streams_verbatim_the_poo": "原样显示完整命令、退出码和两个输出流。pool-admin命令行工具在stdout上以JSON格式报告失败，因此实际消息通常在stdout中。",
  "pool.the_hosts_own_projects": "宿主机各自的项目",
  "pool.the_id_that_answers_at_this_address_now": "当前在此地址响应的标识符。",
  "pool.the_periodic_sweep_is_off_this_page_is_the_only_way_a_scan_runs": "定期扫描已关闭；只能通过此页面运行扫描。",
  "pool.the_prefix_length_must_be_0_to_32": "前缀长度必须介于0到32之间。",
  "pool.the_same_document_command1_serves_from_the_state_dir_on_the_pool_": [
    "与",
    {
      "arg": "command1",
      "type": "token",
      "trust": "internal"
    },
    "提供的文档相同，来自池NAS上的状态目录。"
  ],
  "pool.this_host_answered_but_its_registration_record_could_not_be_read": "此宿主机已响应，但无法读取其注册记录。",
  "pool.this_host_has_not_reported_a_name": "此宿主机尚未报告名称。",
  "pool.this_host_has_not_reported_an_id_so_it_cannot_be_assigned_to_a_po": "此宿主机尚未报告标识符，因此暂时无法分配到池。",
  "pool.this_host_has_not_reported_hardware_facts": "此宿主机尚未报告硬件信息。",
  "pool.this_id_no_longer_answers_at_this_address_the_id_beside_it_does_o": "此标识符已不再在此地址响应；现在响应的是旁边的标识符。一台机器有两个标识符，说明它已重新部署映像或重新克隆。池成员关系仍记录在此标识符下，因此当前在线的宿主机正在池外执行工作。",
  "pool.time_period": "时间段",
  "pool.token_is_right_but_the_clock_is_off_fix_the_host_clock": "令牌正确，但时钟有偏差。请校准宿主机时钟。",
  "pool.total_storage": "总存储容量",
  "pool.type": "类型",
  "pool.unlock": "解锁",
  "pool.unlock_with_the_lab_token_to_see_hostnames": "使用实验室令牌解锁以查看宿主机名称。",
  "pool.unsupported_range": "不支持此范围；请使用1h、24h、7d或30d",
  "pool.uptime": "运行时长",
  "pool.use_this_network": "使用此网络",
  "pool.value1_applied_to_value2_host_s_in_pool_value3": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "：已应用到池“",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "”中的",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "台宿主机。"
  ],
  "pool.value1_host_s": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "台宿主机"
  ],
  "pool.value1_of_value2_checks_failing_pool_control_service_value3_value": [
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "项检查中有",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "项失败。pool-control-service ",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "（",
    {
      "arg": "value4",
      "type": "detail",
      "trust": "external"
    },
    "），采集时间：",
    {
      "arg": "value5",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.value1_of_value2_value3_of_value4_addresses": [
    "对",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "的",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "：",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "/",
    {
      "arg": "value4",
      "type": "detail",
      "trust": "external"
    },
    "个地址。"
  ],
  "pool.value1_value2_applied_value3_failed_value4": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "：",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "项已应用，",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "项失败——",
    {
      "arg": "value4",
      "type": "detail",
      "trust": "external"
    }
  ],
  "pool.version": "版本",
  "pool.what_the_daemon_was_launched_with_and_the_environment_its_pwsh_ch": "守护进程的启动配置及其pwsh子进程继承的环境。",
  "pool.what_to_do": "处理方法",
  "pool.which_build_is_actually_running_and_for_how_long_establishes_whet": "实际运行的构建版本及运行时长，用于确定修复是否已部署。",
  "pool.which_network_cidr_notation": "选择哪个网络？（CIDR表示法）",
  "pool.yuruna_pool_control": "Yuruna池控制"
}
`
