#!/bin/bash
# Version: 2026.09.30
# LICENSEURI https://yuruna.link/license
# Copyright (c) 2019-2026 by Alisson Sol et al.
# Generated by tools/Sync-GuestWorkflows.py; edit guest/shared/ubuntu.update.sh.
set -euo pipefail
workflow="guest/shared/ubuntu.update.sh"
expected="40e040b5adf52e116bccc8f21aa0445acbf756f39e0d58fbeaf0e2ef95e4a6c1"
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ]; then
    local_workflow="$(dirname "${BASH_SOURCE[0]}")/../shared/ubuntu.update.sh"
    if [ -f "$local_workflow" ]; then
        actual=$(sha256sum "$local_workflow")
        [ "${actual%% *}" = "$expected" ] || { echo "Shared workflow checksum mismatch" >&2; exit 3; }
        exec bash "$local_workflow" "$@"
    fi
fi
# Reuse the installed fetcher's host discovery, pinned fallback, and digest gate.
export E_SHA="$expected" EXEC_SHA256="$expected" EXEC_REQUIRE_SHA256=1
exec /usr/local/lib/yuruna/fetch-and-execute.sh "$workflow" "$@"
