apiVersion: v1
kind: Service
metadata:
  name: webchat-backend-service
spec:
  selector:
    app: webchat-backend-pod
  type: NodePort
  ports:
    - protocol: TCP
      name: tcp8000
      port: 8000
      targetPort: 8000
      nodePort: 30800
