# Components information - azure
---
globalVariables:
  DOCKER_SCAN_SUGGEST:   "false"
  containerPrefix:       "yrn42website-prefix"
  registryName:          "componentsRegistry"
  # Notice that the 'registryName' variable is used to find the name of another variable, requiring the dual indirection
  # buildCommand: docker build --rm --build-arg DEV=1 --no-cache -f ${env:dockerfile} -t "${env:containerPrefix}/${env:project}:latest" "${env:buildPath}"
  buildCommand: docker build --rm -f ${env:dockerfile} -t "${env:containerPrefix}/${env:project}:latest" "${env:buildPath}"
  tagCommand: docker tag "${env:containerPrefix}/${env:project}:latest" "$([Environment]::GetEnvironmentVariable("${env:registryName}.registryLocation"))/${env:containerPrefix}/${env:project}:latest"
  pushCommand: docker push "$([Environment]::GetEnvironmentVariable("${env:registryName}.registryLocation"))/${env:containerPrefix}/${env:project}:latest"

components:
- project: "website"
  buildPath: "frontend/website"
  variables:
