# Resources information - azure
---
# TO-SET: azure registry name must be globally unique, without dashes
globalVariables:
  runId:                 "$(-join ((97..122) | Get-Random -Count 6 | %{[char]$_}))"
  runTag:                "azure"
  project:               "cloudtalk"
  namespace:             "${env:project}"
  containerPrefix:       "${env:project}"
  clusterDnsPrefix:      "${env:project}-${env:runId}"
  resourceGroup:         "${env:project}-${env:runId}"
  resourceTags:          "${env:project}-${env:runId}"
  registryName:          "componentsRegistry"
  # regions: az account list-locations -o table
  resourceRegion:        "westus2"
  # https://github.com/Azure/AKS/releases
  # cluster versions: az aks get-versions --location [location] -o table
  clusterVersion:        "1.23.3"
  nodeType:              "Standard_D2_v2"
  nodeCount:             3

# Careful: if the template needs a variable (variables.tf) and it is not defined globally or locally below then the script will be stuck waiting input
resources:
# HACK: create all resource groups first, so they are ready when needed (use the registry creation as a "delay")
- name:                  "defaultResourceGroup"
  template:              "azure/resource-group"
  variables:

- name:                  "rg001"
  template:              "azure/resource-group"
  variables:
    _number:             "001"
    resourceGroup:       "${env:project}-${env:runId}-${env:_number}"
    resourceRegion:      "eastus"

- name:                  "rg002"
  template:              "azure/resource-group"
  variables:
    _number:             "002"
    resourceGroup:       "${env:project}-${env:runId}-${env:_number}"
    resourceRegion:      "northeurope"

- name:                  "rg003"
  template:              "azure/resource-group"
  variables:
    _number:             "003"
    resourceGroup:       "${env:project}-${env:runId}-${env:_number}"
    resourceRegion:      "westus2"

- name:                  "componentsRegistry"
  template:              "azure/registry"
  variables:
    uniqueName:          "${env:project}${env:runId}"

# 001 - eastus
- name:                  "${env:runTag}-${env:project}-${env:runId}-001"
  template:              "azure/aks-cluster"
  variables:
    _number:             "001"
    clusterName:         "${env:project}-${env:runId}-${env:_number}"
    destinationContext:  "${env:runTag}-${env:project}-${env:runId}-${env:_number}"
    resourceGroup:       "${env:project}-${env:runId}-${env:_number}"
    resourceRegion:      "eastus"
    nodeResourceGroup:   "${env:resourceGroup}-aks"

# 002 - northeurope
- name:                  "${env:runTag}-${env:project}-${env:runId}-002"
  template:              "azure/aks-cluster"
  variables:
    _number:             "002"
    clusterName:         "${env:project}-${env:runId}-${env:_number}"
    destinationContext:  "${env:runTag}-${env:project}-${env:runId}-${env:_number}"
    resourceGroup:       "${env:project}-${env:runId}-${env:_number}"
    resourceRegion:      "northeurope"
    nodeResourceGroup:   "${env:resourceGroup}-aks"

# 003 - westus2
- name:                  "${env:runTag}-${env:project}-${env:runId}-003"
  template:              "azure/aks-cluster"
  variables:
    _number:             "003"
    clusterName:         "${env:project}-${env:runId}-${env:_number}"
    destinationContext:  "${env:runTag}-${env:project}-${env:runId}-${env:_number}"
    resourceGroup:       "${env:project}-${env:runId}-${env:_number}"
    resourceRegion:      "westus2"
    nodeResourceGroup:   "${env:resourceGroup}-aks"
