apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values._ironinstance }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values._ironinstance }}
  template:
    metadata:
      labels:
        app: {{ .Values._ironinstance }}
    spec:
      containers:
      - name: ironrslkv
        image: {{ index .Values (printf "%s.registryLocation" .Values.registryName) }}/{{ .Values.containerPrefix }}/ironrslkv:latest
        imagePullPolicy: Always
        ports:
        - name: port-server
          containerPort: {{ .Values._ironServerPort }}
        resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
        env:
          - name: "_ironinstance"
            value: {{ (printf "\"%s\"" .Values._ironinstance) }}
          - name: "_ironClientPort"
            value: {{ (printf "\"%s\"" .Values._ironClientPort) }}
          - name: "_ironServerPort"
            value: {{ (printf "\"%s\"" .Values._ironServerPort) }}
          - name: "ironMachines"
            value: {{ (printf "\"%s\"" .Values.ironMachines) }}
          - name: "certsDir"
            value: {{ .Values.certsDir }}
          - name: "certsServiceFile"
            value: {{ .Values.certsServiceFile }}
          - name: "certsServerFile"
            value: {{ .Values.certsServerFile }}
      imagePullSecrets:
        - name: registry-credential
