// Generated by tools/Invoke-CatalogCompile.ps1 from globalization/catalogs.
// Edit the source catalog and regenerate; changes made here are overwritten.
// locale: en-US  domain: auth

package catalog

// DataenUSauth is the compiled catalog for this locale and domain. It is a
// string so the package carries no init cost until a caller decodes it.
const DataenUSauth = `{
  "auth.attempts_throttled": [
    "too many attempts; wait ",
    {
      "arg": "minutes",
      "type": "integer",
      "trust": "internal"
    },
    " minutes and try again"
  ],
  "auth.bearer_required": "lab auth token required",
  "auth.changes_disabled": "no aggregator URL and no lab auth token configured; changes are disabled",
  "auth.detail_encoding": "request encoding failed",
  "auth.detail_http": [
    "aggregator answered HTTP ",
    {
      "arg": "status",
      "type": "integer",
      "trust": "internal"
    }
  ],
  "auth.detail_malformed_aggregator": "malformed aggregator URL",
  "auth.detail_no_aggregator": "no aggregator URL configured",
  "auth.detail_unconfigured": "no lab auth token and no aggregator URL configured",
  "auth.detail_unreachable": "unreachable",
  "auth.encode_refusal": "the gate could not encode its refusal",
  "auth.login_unavailable": "no aggregator URL is configured, so the pool aggregator cannot check a lab token; actions stay locked",
  "auth.malformed_request": "malformed request body",
  "auth.proof_check_failed": [
    "the control proof could not be checked (",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    },
    "); actions stay locked"
  ],
  "auth.proof_expired": "the control proof is expired or not from this pool",
  "auth.proof_shape": "not a control proof",
  "auth.proof_unconfigured": "no lab auth token and no aggregator URL are configured, so a control proof cannot be checked; actions stay locked",
  "auth.route_disabled": "no lab auth token configured; this route is disabled",
  "auth.session_required": "lab token session or lab auth token required",
  "auth.token_check_failed": [
    "the pool aggregator could not check the lab token (",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    },
    "); actions stay locked"
  ],
  "auth.token_incorrect": "incorrect lab token",
  "auth.token_shape": "the lab token is the 6-character code on the dashboard's Lab token tile"
}
`
