// Generated by tools/Invoke-CatalogCompile.ps1 from globalization/catalogs.
// Edit the source catalog and regenerate; changes made here are overwritten.
// locale: he-IL  domain: stash

package catalog

// DataheILstash is the compiled catalog for this locale and domain. It is a
// string so the package carries no init cost until a caller decodes it.
const DataheILstash = `{
  "stash.all": "הכול",
  "stash.all_hosts": "כל המארחים",
  "stash.all_types": "כל הסוגים",
  "stash.api_could_not_parse_form": "לא ניתן לפענח את הטופס",
  "stash.api_create_detail": [
    "יצירה: ",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.api_detail": [
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.api_invalid_host": "מארח לא תקין",
  "stash.api_invalid_json_body": "גוף JSON לא תקין",
  "stash.api_invalid_stash_path": "נתיב מאגר אחסון לא תקין",
  "stash.api_no_stashes_given": "לא סופקו מאגרי אחסון",
  "stash.api_not_an_archive": "אינו ארכיון",
  "stash.api_not_found": "לא נמצא",
  "stash.api_nothing_to_store_provide_text_or_files": "אין מה לאחסן: ספקו טקסט או קבצים",
  "stash.api_open_archive_detail": [
    "פתיחת ארכיון: ",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.api_open_artifact": "פתיחת תוצר",
  "stash.api_open_upload": "פתיחת העלאה",
  "stash.api_open_uploads": "פתיחת העלאות",
  "stash.api_search_detail": [
    "חיפוש: ",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.api_stash_not_found": "מאגר האחסון לא נמצא",
  "stash.api_stat_artifact": "קבלת מאפייני תוצר",
  "stash.api_too_many_files_in_one_upload": "יותר מדי קבצים בהעלאה אחת",
  "stash.api_too_many_stashes_in_one_request": "יותר מדי מאגרי אחסון בבקשה אחת",
  "stash.archive": "ארכיון",
  "stash.archive_contents": "תוכן הארכיון",
  "stash.archive_value1_contents": [
    "ארכיון (",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    ") -- תוכן:"
  ],
  "stash.audio": "שמע",
  "stash.author_optional": "מחבר (רשות)",
  "stash.choose_at_least_one_file": "בחרו קובץ אחד לפחות.",
  "stash.content": "תוכן",
  "stash.could_not_be_checked": "לא ניתן היה לבדוק",
  "stash.could_not_list_archive_value1": [
    "לא ניתן להציג את רשימת תוכן הארכיון: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.could_not_load_text_http_value1": [
    "לא ניתן לטעון טקסט: HTTP ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.could_not_load_text_value1": [
    "לא ניתן לטעון טקסט: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.create_failed_value1": [
    "היצירה נכשלה: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.create_stash": "צרו מאגר אחסון",
  "stash.created": "נוצר",
  "stash.delete": "מחקו",
  "stash.delete_failed_for_value1_value2": [
    "המחיקה של ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " נכשלה: ",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.delete_failed_value1": [
    "המחיקה נכשלה: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.delete_is_locked_unlock_actions_with_the_lab_token_above_or_open_": "המחיקה נעולה. בטלו את נעילת הפעולות באמצעות אסימון המעבדה שלמעלה, או פתחו דף זה מלוח הבקרה של מארחי Yuruna, שמבטל את הנעילה עבורכם.",
  "stash.delete_is_unavailable_this_service_has_no_pool_aggregator_configu": "המחיקה אינה זמינה: לא הוגדר לשירות זה רכיב צבירה של מאגר, ולכן לא ניתן לבדוק אסימון מעבדה או קישור מלוח הבקרה.",
  "stash.delete_is_unavailable_this_service_has_no_pool_aggregator_configu_9d79c432": " המחיקה אינה זמינה: לא הוגדר לשירות זה רכיב צבירה של מאגר, ולכן לא ניתן לבדוק אסימון מעבדה.",
  "stash.delete_selected": "מחקו את הפריטים שנבחרו",
  "stash.delete_stash_value1": [
    "מחקו את מאגר האחסון ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.delete_stash_value1_this_cannot_be_undone": [
    "מחיקת מאגר האחסון ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " אינה ניתנת לביטול. למחוק?"
  ],
  "stash.delete_stash_value1_value2_value3_this_cannot_be_undone": [
    "מחיקת מאגר האחסון ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " (",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    ", ",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    ") אינה ניתנת לביטול. למחוק?"
  ],
  "stash.delete_value1_this_cannot_be_undone": [
    "מחיקת ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " אינה ניתנת לביטול. למחוק?"
  ],
  "stash.deleting": "המחיקה מתבצעת...",
  "stash.download": "הורידו",
  "stash.error_value1": [
    "שגיאה: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.file_s_multiple_files_are_grouped_into_one_zip": "קבצים -- קבצים מרובים מקובצים לקובץ ZIP אחד",
  "stash.filter_by_content_type": "סננו לפי סוג תוכן",
  "stash.filter_by_host": "סננו לפי מארח",
  "stash.guide": "מדריך",
  "stash.host": "מארח",
  "stash.if_unlocking_answers_that_the_code_could_not_be_checked_the_code_": "אם בניסיון לבטל את הנעילה מתקבלת הודעה שלא ניתן לבדוק את הקוד, הבעיה אינה בקוד -- רכיב הצבירה של המאגר שבודק אותו אינו נגיש, ולא ניתן לבטל את הנעילה עד שיהיה זמין שוב.",
  "stash.image": "תמונה",
  "stash.incomplete_upload_partial_bytes_available_via_download": "העלאה לא שלמה -- חלק מהבתים זמינים באמצעות ״הורידו״.",
  "stash.ips": "כתובות IP:",
  "stash.lab_token": "אסימון מעבדה",
  "stash.listed_count": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "one": [
        "מאגר אחסון ",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " (מוצגים ",
        {
          "arg": "shown",
          "type": "integer",
          "trust": "internal"
        },
        ")"
      ],
      "other": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " מאגרי אחסון (מוצגים ",
        {
          "arg": "shown",
          "type": "integer",
          "trust": "internal"
        },
        ")"
      ],
      "two": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " מאגרי אחסון (מוצגים ",
        {
          "arg": "shown",
          "type": "integer",
          "trust": "internal"
        },
        ")"
      ]
    }
  },
  "stash.load_more": "טענו עוד",
  "stash.loaded": "נטען:",
  "stash.loading": "הטעינה מתבצעת...",
  "stash.local_host_name": [
    {
      "arg": "host",
      "type": "detail",
      "trust": "external"
    },
    "  (מארח זה)"
  ],
  "stash.locked_unlock_actions_with_the_lab_token_above_or_open_this_page_": " נעול -- בטלו את נעילת הפעולות באמצעות אסימון המעבדה שלמעלה, או פתחו דף זה מלוח הבקרה של מארחי Yuruna.",
  "stash.menu": "תפריט",
  "stash.name": "שם",
  "stash.new_stash": "מאגר אחסון חדש",
  "stash.new_stash_yuruna_stash": "מאגר אחסון חדש — Yuruna Stash",
  "stash.no_inline_preview_for_this_type_download_to_view": "אין תצוגה מקדימה בתוך הדף לסוג זה (הורידו כדי לצפות).",
  "stash.no_pool_aggregator_is_configured_so_no_lab_token_can_be_checked_a": [
    "לא הוגדר רכיב צבירה של מאגר, ולכן לא ניתן לבדוק אסימון מעבדה או למחוק דבר כאן. הגדירו ",
    {
      "arg": "command1",
      "type": "token",
      "trust": "internal"
    },
    " בתהליך הרקע כדי לאפשר זאת."
  ],
  "stash.notes_txt": "⁦notes.txt⁩",
  "stash.nothing_to_store_paste_some_content_first": "אין מה לאחסן -- הדביקו תוכן תחילה.",
  "stash.open_on_that_host": "פתחו במארח ההוא",
  "stash.open_pdf": "פתחו PDF",
  "stash.other": "אחר",
  "stash.pages": "דפים",
  "stash.paste_content_here": "הדביקו תוכן כאן...",
  "stash.paste_text": "הדביקו טקסט",
  "stash.pause": "השהיה",
  "stash.pdf": "מסמך PDF",
  "stash.permalink": "קישור קבוע",
  "stash.preview_truncated_download_for_the_full_content": "התצוגה המקדימה נקטעה -- בחרו ״הורידו״ לקבלת התוכן המלא.",
  "stash.preview_unavailable_use_download_to_open_the_file": "התצוגה המקדימה אינה זמינה. בחרו ״הורידו״ כדי לפתוח את הקובץ.",
  "stash.received": "התקבל",
  "stash.received_by_host": " התקבל על ידי המארח ",
  "stash.received_host": [
    "התקבל אצל המארח ",
    {
      "arg": "host",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.refresh": "רעננו",
  "stash.rescan_the_stash_share_for_other_hosts_stashes": "סרקו מחדש את השיתוף של מאגר האחסון לאיתור מאגרי אחסון של מארחים אחרים",
  "stash.scp_path": "נתיב SCP",
  "stash.search_id_filename_user_path": "חפשו מזהה, שם קובץ, משתמש, נתיב...",
  "stash.select_stash_value1": [
    "בחרו את מאגר האחסון ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.selection_count": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "one": [
        "מאגר אחסון ",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        }
      ],
      "other": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " מאגרי אחסון"
      ],
      "two": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " מאגרי אחסון"
      ]
    }
  },
  "stash.short_link": "קישור קצר",
  "stash.six_character_lab_token_from_the_dashboard": "אסימון מעבדה בן שישה תווים מלוח הבקרה",
  "stash.size": "גודל",
  "stash.source": "מקור",
  "stash.stash": "מאגר אחסון",
  "stash.stash_not_found": "מאגר האחסון לא נמצא.",
  "stash.stash_text_preview": "תצוגה מקדימה של הטקסט במאגר האחסון",
  "stash.stash_yuruna_stash": "מאגר אחסון — Yuruna Stash",
  "stash.stashes": "מאגרי אחסון",
  "stash.stashes_yuruna_stash": "מאגרי אחסון — Yuruna Stash",
  "stash.state_archive": "ארכיון",
  "stash.state_audio": "שמע",
  "stash.state_complete": "הושלם",
  "stash.state_image": "תמונה",
  "stash.state_other": "אחר",
  "stash.state_partial": "חלקי",
  "stash.state_pdf": "מסמך PDF",
  "stash.state_pending": "בהמתנה",
  "stash.state_text": "טקסט",
  "stash.state_truncated": "נקטע",
  "stash.state_video": "וידאו",
  "stash.status": "מצב",
  "stash.still_receiving_no_preview_yet": "הקבלה עדיין מתבצעת -- אין עדיין תצוגה מקדימה.",
  "stash.text": "טקסט",
  "stash.the_6_character_code_on_the_yuruna_hosts_dashboard_s_lab_token_ti": "הקוד בן 6 התווים באריח אסימון המעבדה בלוח הבקרה של מארחי Yuruna; אפשר להשתמש באותיות גדולות או קטנות. פתיחת דף זה מלוח הבקרה מבטלת את הנעילה ללא הקוד. נדרש רק למחיקה.",
  "stash.this_host": "מארח זה",
  "stash.title_filename_optional": "כותרת / שם קובץ (רשות)",
  "stash.truncated_at_the_100_mb_cap_download_serves_the_capped_artifact": "נקטע במגבלת 100 MB -- ״הורידו״ מספק את התוצר שנחתך בהתאם למגבלה.",
  "stash.type": "סוג",
  "stash.unlock_actions": "בטלו את נעילת הפעולות",
  "stash.unlock_actions_to_delete": "בטלו את נעילת הפעולות כדי למחוק",
  "stash.unnamed": "(ללא שם)",
  "stash.upload_file_s": "העלו קבצים",
  "stash.upload_stash": "העלו מאגר אחסון",
  "stash.user": "משתמש",
  "stash.value1_malformed_permalink": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " (קישור קבוע פגום)"
  ],
  "stash.value1_of_value2_could_not_be_deleted_value3": [
    "לא ניתן למחוק ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " מתוך ",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    " -- ",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.value1_pdf_preview": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " (תצוגה מקדימה של PDF)"
  ],
  "stash.value1_yuruna_stash": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " -- מאגר אחסון Yuruna Stash"
  ],
  "stash.video": "וידאו",
  "stash.web": "אינטרנט",
  "stash.yuruna_stash": "מאגר אחסון Yuruna Stash",
  "stash.yuruna_stash_service": "שירות Yuruna stash service"
}
`
