// Generated by tools/Invoke-CatalogCompile.ps1 from globalization/catalogs.
// Edit the source catalog and regenerate; changes made here are overwritten.
// locale: zh-CN  domain: stash

package catalog

// DatazhCNstash is the compiled catalog for this locale and domain. It is a
// string so the package carries no init cost until a caller decodes it.
const DatazhCNstash = `{
  "stash.all": "全部",
  "stash.all_hosts": "所有宿主机",
  "stash.all_types": "所有类型",
  "stash.api_could_not_parse_form": "无法解析表单",
  "stash.api_create_detail": [
    "创建：",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.api_detail": [
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.api_invalid_host": "宿主机无效",
  "stash.api_invalid_json_body": "JSON正文无效",
  "stash.api_invalid_stash_path": "存储服务路径无效",
  "stash.api_no_stashes_given": "未提供存储服务",
  "stash.api_not_an_archive": "不是归档文件",
  "stash.api_not_found": "未找到",
  "stash.api_nothing_to_store_provide_text_or_files": "没有可存储的内容：请提供文本或文件",
  "stash.api_open_archive_detail": [
    "打开归档文件：",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.api_open_artifact": "打开制品",
  "stash.api_open_upload": "打开上传文件",
  "stash.api_open_uploads": "打开上传文件",
  "stash.api_search_detail": [
    "搜索：",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.api_stash_not_found": "未找到存储服务",
  "stash.api_stat_artifact": "获取制品状态",
  "stash.api_too_many_files_in_one_upload": "单次上传的文件过多",
  "stash.api_too_many_stashes_in_one_request": "单次请求的存储服务过多",
  "stash.archive": "压缩包",
  "stash.archive_contents": "归档内容",
  "stash.archive_value1_contents": [
    "归档（",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "）——内容："
  ],
  "stash.audio": "音频",
  "stash.author_optional": "作者（可选）",
  "stash.choose_at_least_one_file": "请至少选择一个文件。",
  "stash.content": "内容",
  "stash.could_not_be_checked": "无法检查",
  "stash.could_not_list_archive_value1": [
    "无法列出归档内容：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.could_not_load_text_http_value1": [
    "无法加载文本：HTTP ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.could_not_load_text_value1": [
    "无法加载文本：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.create_failed_value1": [
    "创建失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.create_stash": "创建存储服务",
  "stash.created": "创建时间",
  "stash.delete": "删除",
  "stash.delete_failed_for_value1_value2": [
    "删除",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "失败：",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.delete_failed_value1": [
    "删除失败：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.delete_is_locked_unlock_actions_with_the_lab_token_above_or_open_": "删除操作已锁定。请使用上方的实验室令牌解锁操作，或从Yuruna宿主机仪表板打开此页面以自动解锁。",
  "stash.delete_is_unavailable_this_service_has_no_pool_aggregator_configu": "删除功能不可用：此服务未配置池聚合器，因此无法验证实验室令牌或仪表板链接。",
  "stash.delete_is_unavailable_this_service_has_no_pool_aggregator_configu_9d79c432": " 删除功能不可用：此服务未配置池聚合器，因此无法验证实验室令牌。",
  "stash.delete_selected": "删除所选项",
  "stash.delete_stash_value1": [
    "删除存储服务",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.delete_stash_value1_this_cannot_be_undone": [
    "将删除存储服务",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "，此操作无法撤销。是否继续？"
  ],
  "stash.delete_stash_value1_value2_value3_this_cannot_be_undone": [
    "将删除存储服务",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "（",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "，",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "），此操作无法撤销。是否继续？"
  ],
  "stash.delete_value1_this_cannot_be_undone": [
    "将删除",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "，此操作无法撤销。是否继续？"
  ],
  "stash.deleting": "正在删除……",
  "stash.download": "下载",
  "stash.error_value1": [
    "错误：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.file_s_multiple_files_are_grouped_into_one_zip": "文件——多个文件会打包为一个ZIP文件",
  "stash.filter_by_content_type": "按内容类型筛选",
  "stash.filter_by_host": "按宿主机筛选",
  "stash.guide": "指南",
  "stash.host": "宿主机",
  "stash.if_unlocking_answers_that_the_code_could_not_be_checked_the_code_": "如果解锁时提示无法验证代码，问题不在代码，而是无法连接到负责验证的池聚合器。请等待池聚合器恢复后再解锁。",
  "stash.image": "图像",
  "stash.incomplete_upload_partial_bytes_available_via_download": "上传未完成——可通过“下载”获取已上传的部分字节。",
  "stash.ips": "IP地址：",
  "stash.lab_token": "实验室令牌",
  "stash.listed_count": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        "共",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "个存储服务（显示",
        {
          "arg": "shown",
          "type": "integer",
          "trust": "internal"
        },
        "个）"
      ]
    }
  },
  "stash.load_more": "加载更多",
  "stash.loaded": "已加载：",
  "stash.loading": "正在加载……",
  "stash.local_host_name": [
    {
      "arg": "host",
      "type": "detail",
      "trust": "external"
    },
    "（本宿主机）"
  ],
  "stash.locked_unlock_actions_with_the_lab_token_above_or_open_this_page_": " 已锁定——请使用上方的实验室令牌解锁操作，或从Yuruna宿主机仪表板打开此页面。",
  "stash.menu": "菜单",
  "stash.name": "名称",
  "stash.new_stash": "新建存储服务",
  "stash.new_stash_yuruna_stash": "新建存储服务——Yuruna Stash",
  "stash.no_inline_preview_for_this_type_download_to_view": "此类型不支持内嵌预览（请下载后查看）。",
  "stash.no_pool_aggregator_is_configured_so_no_lab_token_can_be_checked_a": [
    "未配置池聚合器，因此无法验证实验室令牌，也无法删除此处的任何内容。请在守护进程中设置",
    {
      "arg": "command1",
      "type": "token",
      "trust": "internal"
    },
    "以启用删除功能。"
  ],
  "stash.notes_txt": "notes.txt",
  "stash.nothing_to_store_paste_some_content_first": "没有可存储的内容——请先粘贴内容。",
  "stash.open_on_that_host": "在该宿主机上打开",
  "stash.open_pdf": "打开PDF",
  "stash.other": "其他",
  "stash.pages": "页面",
  "stash.paste_content_here": "在此粘贴内容……",
  "stash.paste_text": "粘贴文本",
  "stash.pause": "暂停",
  "stash.pdf": "PDF文档",
  "stash.permalink": "永久链接",
  "stash.preview_truncated_download_for_the_full_content": "预览已截断——请选择“下载”获取完整内容。",
  "stash.preview_unavailable_use_download_to_open_the_file": "预览不可用。请选择“下载”打开文件。",
  "stash.received": "已接收",
  "stash.received_by_host": " 接收宿主机：",
  "stash.received_host": [
    "已由宿主机",
    {
      "arg": "host",
      "type": "detail",
      "trust": "external"
    },
    "接收"
  ],
  "stash.refresh": "刷新",
  "stash.rescan_the_stash_share_for_other_hosts_stashes": "重新扫描存储服务共享目录，查找其他宿主机的存储服务",
  "stash.scp_path": "SCP路径",
  "stash.search_id_filename_user_path": "搜索标识符、文件名、用户、路径……",
  "stash.select_stash_value1": [
    "选择存储服务",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.selection_count": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "个存储服务"
      ]
    }
  },
  "stash.short_link": "短链接",
  "stash.six_character_lab_token_from_the_dashboard": "仪表板上的六字符实验室令牌",
  "stash.size": "大小",
  "stash.source": "来源",
  "stash.stash": "存储服务",
  "stash.stash_not_found": "未找到存储服务。",
  "stash.stash_text_preview": "存储服务文本预览",
  "stash.stash_yuruna_stash": "存储服务——Yuruna Stash",
  "stash.stashes": "存储服务",
  "stash.stashes_yuruna_stash": "存储服务——Yuruna Stash",
  "stash.state_archive": "归档",
  "stash.state_audio": "音频",
  "stash.state_complete": "已完成",
  "stash.state_image": "图像",
  "stash.state_other": "其他",
  "stash.state_partial": "部分完成",
  "stash.state_pdf": "pdf文档",
  "stash.state_pending": "待处理",
  "stash.state_text": "文本",
  "stash.state_truncated": "已截断",
  "stash.state_video": "视频",
  "stash.status": "状态",
  "stash.still_receiving_no_preview_yet": "仍在接收——暂时无法预览。",
  "stash.text": "文本",
  "stash.the_6_character_code_on_the_yuruna_hosts_dashboard_s_lab_token_ti": "Yuruna宿主机仪表板“实验室令牌”卡片上的6字符代码，大小写均可。从该仪表板打开此页面即可解锁，无需输入代码。仅删除时需要。",
  "stash.this_host": "本宿主机",
  "stash.title_filename_optional": "标题／文件名（可选）",
  "stash.truncated_at_the_100_mb_cap_download_serves_the_capped_artifact": "已在100 MB上限处截断——“下载”提供截断后的制品。",
  "stash.type": "类型",
  "stash.unlock_actions": "解锁操作",
  "stash.unlock_actions_to_delete": "解锁操作以删除",
  "stash.unnamed": "（未命名）",
  "stash.upload_file_s": "上传文件",
  "stash.upload_stash": "上传存储服务",
  "stash.user": "用户",
  "stash.value1_malformed_permalink": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "（永久链接格式错误）"
  ],
  "stash.value1_of_value2_could_not_be_deleted_value3": [
    "共",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "项，其中",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "项无法删除——",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    }
  ],
  "stash.value1_pdf_preview": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "（PDF预览）"
  ],
  "stash.value1_yuruna_stash": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " -- Yuruna Stash（存储服务）"
  ],
  "stash.video": "视频",
  "stash.web": "网页",
  "stash.yuruna_stash": "Yuruna Stash（存储服务）",
  "stash.yuruna_stash_service": "Yuruna stash service（存储服务）"
}
`
