# Resources information - localhost
---
globalVariables:
  runId:                 "$(-join ((97..122) | Get-Random -Count 6 | %{[char]$_}))"
  runTag:                "localhost"
  project:               "webchat"
  namespace:             "${env:project}"
  containerPrefix:       "${env:project}"
  clusterDnsPrefix:      "${env:project}-${env:runId}"
  resourceGroup:         "${env:project}-${env:runId}"
  resourceTags:          "${env:project}-${env:runId}"
  registryName:          "componentsRegistry"
  sourceContext:         "docker-desktop"

resources:
- name:                  "componentsRegistry"
  template:              "localhost/registry"
  variables:
    uniqueName:          "${env:project}${env:runId}"

- name:                  "${env:runTag}-${env:project}-${env:runId}"
  template:              "localhost/context-copy"
  variables:
    clusterName:         "${env:project}-${env:runId}"
    destinationContext:  "${env:runTag}-${env:project}-${env:runId}"
