// Generated by tools/Invoke-CatalogEmbed.ps1 from globalization/locale-manifest.json.
// Edit the manifest and re-run that tool; changes made here are overwritten.

package i18n

// generatedLocaleData is every locale the manifest declares, including the
// pseudo locales. Being present here does not make a locale selectable: only
// generatedSupported decides that.
var generatedLocaleData = map[string]LocaleData{
	"en-US":     {Group: ",", Decimal: ".", GroupSize: 3, PluralRule: "one-if-1", Direction: "ltr"},
	"pt-BR":     {Group: ".", Decimal: ",", GroupSize: 3, PluralRule: "", Direction: "ltr"},
	"qps-Ploc":  {Group: ",", Decimal: ".", GroupSize: 3, PluralRule: "one-if-1", Direction: "ltr"},
	"qps-Plocm": {Group: ",", Decimal: ".", GroupSize: 3, PluralRule: "one-if-1", Direction: "rtl"},
}

// generatedSupported is the set a request may actually resolve to. A locale
// whose catalog is not reviewed is not in it, however complete its data looks.
var generatedSupported = []string{
	"en-US",
}

// generatedPseudo is the locales that exist only to make a translation
// problem visible: expanded text that overflows a fixed box, and mirrored
// text that exposes a hard-coded direction. They are never negotiable in a
// release build -- a reader who received one would think the page was broken.
var generatedPseudo = []string{
	"qps-Ploc",
	"qps-Plocm",
}

// generatedAliases maps a canonical tag the manifest does not ship to the one
// it says answers for it. Keys are lowercased for lookup.
var generatedAliases = map[string]string{
	"en":    "en-US",
	"pt":    "pt-BR",
	"pt-pt": "pt-BR",
}

const generatedDefault = "en-US"
const generatedMaxTagLength = 35
const generatedMaxHeaderLength = 512

const generatedCatalogVersion = "2026.09.08"
const generatedCatalogHash = "cc8d2445c261ebc2b199f6537f722c79a06a08150fefa7ccaca61bd248929f1c"
