// Generated by tools/Invoke-CatalogCompile.ps1 from globalization/catalogs.
// Edit the source catalog and regenerate; changes made here are overwritten.
// locale: he-IL  domain: parser

package catalog

// DataheILparser is the compiled catalog for this locale and domain. It is a
// string so the package carries no init cost until a caller decodes it.
const DataheILparser = `{
  "parser.bytes": "בתים",
  "parser.client": "לקוח",
  "parser.method": "שיטה",
  "parser.pause_auto_refresh": "השהו רענון אוטומטי",
  "parser.refresh_failed": "(הרענון נכשל)",
  "parser.refresh_failed_the_rows_below_are_from_the_last_successful_read": "הרענון נכשל. השורות הבאות הן מהקריאה האחרונה שהצליחה.",
  "parser.refreshed_rows": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "one": [
        "(שורה ",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        ", רוענן ",
        {
          "arg": "time",
          "type": "text",
          "trust": "internal"
        },
        ")"
      ],
      "other": [
        "(",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " שורות, רוענן ",
        {
          "arg": "time",
          "type": "text",
          "trust": "internal"
        },
        ")"
      ],
      "two": [
        "(",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " שורות, רוענן ",
        {
          "arg": "time",
          "type": "text",
          "trust": "internal"
        },
        ")"
      ]
    }
  },
  "parser.resume_auto_refresh": "חדשו רענון אוטומטי",
  "parser.squid_cache_recent_100_requests": "מטמון Squid -- 100 הבקשות האחרונות",
  "parser.status": "מצב",
  "parser.time": "זמן",
  "parser.url": "כתובת אינטרנט",
  "parser.user_agent": "סוכן משתמש (user-agent)"
}
`
