// Generated by tools/Invoke-CatalogCompile.ps1 from globalization/catalogs.
// Edit the source catalog and regenerate; changes made here are overwritten.
// locale: zh-CN  domain: parser

package catalog

// DatazhCNparser is the compiled catalog for this locale and domain. It is a
// string so the package carries no init cost until a caller decodes it.
const DatazhCNparser = `{
  "parser.bytes": "字节",
  "parser.client": "客户端",
  "parser.method": "方法",
  "parser.pause_auto_refresh": "暂停自动刷新",
  "parser.refresh_failed": "（刷新失败）",
  "parser.refresh_failed_the_rows_below_are_from_the_last_successful_read": "刷新失败。以下各行来自上次成功读取的数据。",
  "parser.refreshed_rows": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "other": [
        "（",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        "行，刷新时间：",
        {
          "arg": "time",
          "type": "text",
          "trust": "internal"
        },
        "）"
      ]
    }
  },
  "parser.resume_auto_refresh": "恢复自动刷新",
  "parser.squid_cache_recent_100_requests": "Squid缓存——最近100个请求",
  "parser.status": "状态",
  "parser.time": "时间",
  "parser.url": "网址（url）",
  "parser.user_agent": "用户代理（user-agent）"
}
`
