// Generated by tools/Invoke-CatalogEmbed.ps1 from globalization/kernel/yuruna.fetch-shim.js and globalization/kernel/yuruna.rawpage.js.
// Edit those sources and re-run the tool; changes made here are overwritten.

package main

// requestAdapterScript is the ES5 stand-in this service's pages install before
// their own script. These pages are string literals and load no shared runtime,
// so the adapter every other page inherits has to travel with them.
const requestAdapterScript = `// From globalization/kernel/yuruna.fetch-shim.js -- see that file for why.
(function (window) {
  'use strict';

  // Only the STAND-IN is conditional. Everything below it is defined either
  // way: an early return here would leave yurunaRequest undefined on every
  // browser that has a native fetch, which is almost all of them, and the
  // pages that call it would fail on the modern browsers rather than the old
  // one this file exists for.
  if (!window.fetch) {
    window.fetch = function (url, options) {
      options = options || {};
      return new Promise(function (resolve, reject) {
        var xhr = new XMLHttpRequest();
        xhr.open(options.method || 'GET', url, true);
        var headers = options.headers;
        if (headers) {
          for (var k in headers) {
            if (Object.prototype.hasOwnProperty.call(headers, k)) { xhr.setRequestHeader(k, headers[k]); }
          }
        }
        xhr.onload = function () {
          var body = xhr.responseText;
          resolve({
            ok: xhr.status >= 200 && xhr.status < 300,
            status: xhr.status,
            statusText: xhr.statusText,
            text: function () { return Promise.resolve(body); },
            json: function () {
              return new Promise(function (res, rej) {
                try { res(JSON.parse(body)); } catch (e) { rej(e); }
              });
            }
          });
        };
        xhr.onerror = function () { reject(new Error('Network error')); };
        // abort() fires onabort, not onerror. Without this the promise of an
        // abandoned request stays pending for the life of the page, and whatever
        // is waiting on it is never told anything.
        xhr.onabort = function () { reject(new Error('The request was given up on.')); };
        // Handed out so a caller can abandon a stalled request. The native path
        // uses AbortController for the same job; this is the only handle that
        // exists when there is no native fetch to attach a signal to.
        if (options.yurunaXhrOut) { options.yurunaXhrOut(xhr); }
        xhr.send(options.body || null);
      });
    };
  }
}(window));
// From globalization/kernel/yuruna.rawpage.js -- see that file for why.
(function (window) {
  'use strict';

  //
  // The timer settles the caller's promise itself rather than waiting for the
  // transport to fail. Between the two supported edges there is a browser with
  // a native fetch and no AbortController: nothing there can cancel the
  // request, and a timeout that could only abort would leave the caller
  // waiting forever on a promise that never settles -- a hang wearing a
  // timeout's clothes. Cancellation is still attempted where it is possible,
  // so the socket is freed; the caller is answered on time either way.
  window.yurunaRequest = function (url, timeoutMs) {
    var ms = timeoutMs > 0 ? timeoutMs : 10000;
    var controller = (typeof window.AbortController !== 'undefined') ? new window.AbortController() : null;
    var init = {};
    var xhr = null;
    if (controller) { init.signal = controller.signal; }
    else { init.yurunaXhrOut = function (x) { xhr = x; }; }

    return new Promise(function (resolve, reject) {
      var done = false;
      var timer = null;
      var finish = function (settle, value) {
        if (done) { return; }
        done = true;
        if (timer) { window.clearTimeout(timer); timer = null; }
        settle(value);
      };
      timer = window.setTimeout(function () {
        if (controller) { controller.abort(); }
        else if (xhr && xhr.abort) { try { xhr.abort(); } catch (e) { /* already done */ } }
        finish(reject, new Error('The request took too long and was given up on.'));
      }, ms);
      window.fetch(url, init).then(function (r) {
        if (!r.ok) { throw new Error('HTTP ' + r.status); }
        return r.json();
      }).then(function (data) {
        finish(resolve, data);
      }, function (e) {
        finish(reject, e);
      });
    });
  };

  // The time alone, in a shape that does not change with the reader's device.
  //
  // toLocaleTimeString is the obvious call and the wrong one: at the floor it
  // ignores the locale it is handed and answers in the browser's own, so the
  // refresh stamp on a page served in one language is written in another --
  // and the page has no shared runtime to borrow a formatter from.
  window.yurunaLocalTime = function (value) {
    var when = (value instanceof Date) ? value : new Date(value);
    if (isNaN(when.getTime())) { return ''; }
    var pad = function (n) { return n < 10 ? '0' + n : '' + n; };
    return pad(when.getHours()) + ':' + pad(when.getMinutes()) + ':' + pad(when.getSeconds());
  };
}(window));`
