<#PSScriptInfo
.VERSION 2026.09.08
.GUID 42d7a1c5-8e60-4b3f-9a52-6cb0f4e21d78
.AUTHOR Alisson Sol et al.
.COPYRIGHT (c) 2019-2026 by Alisson Sol et al.
.TAGS yuruna globalization catalog browser embed es5
.LICENSEURI https://yuruna.link/license
.PROJECTURI https://yuruna.com
.ICONURI
.EXTERNALMODULEDEPENDENCIES
.REQUIREDSCRIPTS
.EXTERNALSCRIPTDEPENDENCIES
.RELEASENOTES
.PRIVATEDATA
#>

#requires -version 7

<#
.SYNOPSIS
    Copy the catalog kernel, the locale data and the default-locale message
    tables into every browser runtime that renders Yuruna text.
.DESCRIPTION
    A status page loads exactly one script. Anything the page needs in order to
    render its first label has to already be inside that script, or the label
    arrives after the paint that was supposed to show it -- and on the floor
    browser there is no module loader to arrange otherwise. So the kernel and
    the default locale are copied in, and only a reader who asks for a
    non-default language costs the page an extra request.

    Both runtimes get the same bytes from the same sources: the kernel from
    globalization/kernel, the tables from what the catalog compiler generated.
    Two copies of a file diverge the moment someone edits the near one, which
    is why -Check exists and why the suite runs it.

    Regenerating is safe to repeat: the block between the markers is replaced
    whole, so running twice leaves the same file.
.PARAMETER Check
    Report what would change and exit non-zero instead of writing. For the gate.
.PARAMETER Quiet
    Print only findings.
.EXAMPLE
    pwsh -File tools/Invoke-CatalogEmbed.ps1
.EXAMPLE
    pwsh -File tools/Invoke-CatalogEmbed.ps1 -Check
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [switch]$Check,
    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$KernelPath = Join-Path $RepoRoot 'globalization/kernel/yuruna.i18n.js'
$ManifestPath = Join-Path $RepoRoot 'globalization/locale-manifest.json'
$GeneratedBrowser = Join-Path $RepoRoot 'globalization/generated/browser'

$BeginMarker = '// >>> yuruna-i18n embedded block -- generated by tools/Invoke-CatalogEmbed.ps1'
$EndMarker = '// <<< yuruna-i18n embedded block'

# Which runtime carries which domains. A binary embeds only what its own pages
# render; a domain added here is bytes on every page that loads the runtime.
$Targets = @(
    @{ Path = 'test/status/yuruna.common.js'; Domains = @('status') }
    @{ Path = 'test/extension/extension-sdk/webui/assets/yuruna.core.js'; Domains = @('status') }
    # The pool domain rides pool-control's OWN script, not the shared runtime.
    # Every extension service loads the shared one, so a domain only one of
    # them renders would be bytes on every other service's pages for messages
    # none of them ask for.
    @{ Path = 'test/extension/pool-control-service/server/internal/httpsrv/web/assets/common.js'
       Domains = @('pool'); DomainsOnly = $true }
)

# The Go tree is a set of independent modules, so a service cannot import a
# package that lives outside its own. Each consumer gets the compiled data
# copied in beside it instead, carrying only the domains that binary renders --
# a domain listed here is bytes in that service's image.
#
# The pseudo locales travel with the real one on purpose: the reference slice
# has to be answerable in expanded and mirrored pseudo, and a locale that is
# not in the binary cannot be requested from it.
$GoTargets = @(
    @{
        Module   = 'test/extension/pool-control-service/server'
        Package  = 'internal/catalog'
        Domains  = @('status', 'pool')
        Locales  = @('en-US', 'qps-Ploc', 'qps-Plocm')
    }
)

# Non-default browser catalogs are separate parser-discovered assets. Keep the
# compiler output as the single source and copy only the domains each shipped
# reference page can render. The default locale remains embedded in its
# existing runtime and therefore adds no request.
$BrowserCatalogTargets = @(
    @{ Source = 'qps-Ploc.status.js';  Destination = 'test/status/qps-Ploc.status.js' }
    @{ Source = 'qps-Plocm.status.js'; Destination = 'test/status/qps-Plocm.status.js' }
    @{ Source = 'qps-Ploc.pool.js';    Destination = 'test/extension/pool-control-service/server/internal/httpsrv/web/assets/qps-Ploc.pool.js' }
    @{ Source = 'qps-Plocm.pool.js';   Destination = 'test/extension/pool-control-service/server/internal/httpsrv/web/assets/qps-Plocm.pool.js' }
)

# The two services whose pages are Go string literals and load no shared
# runtime. Their application scripts call fetch, so without an adapter they
# render their shell and then fill in nothing on a floor browser -- an empty
# table that reads as a lab with no data rather than as a page that failed.
#
# It is copied rather than imported because one of these modules deliberately
# depends on nothing: its guest build does not stage the SDK beside it, so a
# module dependency would break the build it is supposed to protect.
# Every page needs the stand-in. Only a page with no shared runtime needs its
# own timeout, so the bounded helper is composed on for those two and left out
# of the runtimes -- shipping it there would put bytes on every extension page
# for code none of them call.
$FetchShimSource = 'globalization/kernel/yuruna.fetch-shim.js'
$RawPageSource = 'globalization/kernel/yuruna.rawpage.js'
$RequestAdapterTargets = @(
    @{ Module = 'test/extension/caching-proxy-service';        File = 'requestadapter.go'; Package = 'main' }
    @{ Module = 'test/extension/caching-proxy-parser-service'; File = 'requestadapter.go'; Package = 'main' }
)

# Where the shared locale table lands. Every Go service reaches this through
# the SDK it already depends on, so this one is not copied per module.
$SdkLocaleData = 'test/extension/extension-sdk/i18n/localedata.go'

function Get-CodeAfterHeader {
    <#
    .SYNOPSIS
        One source file with its leading comment header removed.
    .DESCRIPTION
        The header explains why the file is shaped the way it is, at the length
        that reasoning deserves. That belongs in the source, not on the wire:
        embedded verbatim into every runtime it is bytes each reader downloads
        to render nothing. The embedded copy carries a pointer to the file that
        holds the explanation instead.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][string]$Text)

    $lines = ($Text -replace "`r`n", "`n") -split "`n"
    $i = 0
    while ($i -lt $lines.Count) {
        $trimmed = $lines[$i].Trim()
        if ($trimmed -eq '' -or $trimmed.StartsWith('//')) { $i++; continue }
        break
    }
    return (($lines[$i..($lines.Count - 1)]) -join "`n").TrimEnd()
}

function Get-EmbeddedBlock {
    <#
    .SYNOPSIS
        The exact text that belongs between the markers for one runtime.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][AllowEmptyCollection()][string[]]$Domains, [switch]$DomainsOnly)

    $manifest = ConvertFrom-Json -InputObject ([IO.File]::ReadAllText($ManifestPath))
    $default = [string]$manifest.default

    $sb = [Text.StringBuilder]::new()
    [void]$sb.AppendLine($BeginMarker)
    [void]$sb.AppendLine('// Edit globalization/kernel/yuruna.i18n.js or the catalog sources, then re-run')
    [void]$sb.AppendLine('// that tool. An edit made here is overwritten and the drift gate fails first.')

    # The locale data: separators, plural rule and direction, declared in the
    # manifest so all three runtimes answer the same for the same number.
    $data = [ordered]@{}
    $aliases = [ordered]@{}
    $enabled = [ordered]@{}
    foreach ($name in ($manifest.locales.PSObject.Properties.Name | Sort-Object)) {
        $locale = $manifest.locales.$name
        $nf = $locale.numberFormat
        $data[$name] = [ordered]@{
            group     = [string]$nf.group
            decimal   = [string]$nf.decimal
            groupSize = [int]$nf.groupSize
            plural    = if ($null -eq $locale.pluralRule) { $null } else { [string]$locale.pluralRule }
            direction = [string]$locale.direction
        }
        # Locale data exists before a locale is deliverable so its formatting
        # can be reviewed. Selection authority is narrower: supported locales
        # plus test-only pseudo locales. A planned locale with an unpinned
        # plural rule must not become selectable merely because this table
        # contains its separators.
        if ([string]$locale.status -in @('supported', 'pseudo')) {
            $enabled[$name.ToLowerInvariant()] = $name
        }
    }
    foreach ($p in ($manifest.aliases.PSObject.Properties | Sort-Object Name)) {
        $aliases[$p.Name.ToLowerInvariant()] = [string]$p.Value
    }

    # A script whose page already loaded a runtime gets the message tables and
    # nothing else. Repeating the kernel, the stand-in and the locale table
    # there would be twenty-odd kilobytes every page of that service downloads
    # to define what the previous script already defined.
    if (-not $DomainsOnly) {
        $setPath = Join-Path $RepoRoot 'globalization/manifests/catalog-set.json'
        $catalogProvenance = [ordered]@{ version = ''; hash = '' }
        if (Test-Path -LiteralPath $setPath -PathType Leaf) {
            $setBytes = [IO.File]::ReadAllBytes($setPath)
            $sha = [Security.Cryptography.SHA256]::Create()
            try {
                $catalogProvenance.hash = [BitConverter]::ToString($sha.ComputeHash($setBytes)).Replace('-', '').ToLowerInvariant()
            } finally { $sha.Dispose() }
            $setDoc = ConvertFrom-Json -InputObject ([Text.UTF8Encoding]::new($false).GetString($setBytes))
            $catalogProvenance.version = [string]$setDoc.compilerVersion
        }
        [void]$sb.AppendLine('(function (root) {')
        [void]$sb.AppendLine("  'use strict';")
        [void]$sb.AppendLine('  root.YurunaLocaleData = ' + (ConvertTo-Json -InputObject $data -Depth 6 -Compress) + ';')
        [void]$sb.AppendLine('  root.YurunaEnabledLocales = ' + (ConvertTo-Json -InputObject $enabled -Depth 3 -Compress) + ';')
        [void]$sb.AppendLine('  root.YurunaLocaleAliases = ' + (ConvertTo-Json -InputObject $aliases -Depth 4 -Compress) + ';')
        [void]$sb.AppendLine('  root.YurunaCatalogProvenance = ' + (ConvertTo-Json -InputObject $catalogProvenance -Depth 3 -Compress) + ';')
        [void]$sb.AppendLine('}(typeof window !== ' + "'undefined'" + ' ? window : this));')
    }

    # The default locale's tables, verbatim from what the compiler generated.
    # Taking the compiler's own bytes rather than re-serializing here is what
    # makes "the page shows what the catalog says" checkable by comparison.
    foreach ($domain in ($Domains | Sort-Object)) {
        $artifact = Join-Path $GeneratedBrowser "$default.$domain.js"
        if (-not (Test-Path -LiteralPath $artifact -PathType Leaf)) {
            throw "No compiled browser artifact for '$default.$domain'. Run tools/Invoke-CatalogCompile.ps1 first."
        }
        [void]$sb.AppendLine(([IO.File]::ReadAllText($artifact)).TrimEnd())
    }

    # The request adapter travels with the kernel so there is one copy of it
    # across both browser runtimes and both raw Go pages. It installs itself
    # only when the browser has no fetch, so a modern browser pays nothing.
    if (-not $DomainsOnly) {
        [void]$sb.AppendLine('// The fetch stand-in, from ' + $FetchShimSource + ' -- see that file for why.')
        [void]$sb.AppendLine((Get-CodeAfterHeader -Text ([IO.File]::ReadAllText((Join-Path $RepoRoot $FetchShimSource)))))
        [void]$sb.AppendLine(([IO.File]::ReadAllText($KernelPath)).TrimEnd())
    }
    [void]$sb.Append($EndMarker)
    return ($sb.ToString() -replace "`r`n", "`n")
}

function Get-UpdatedRuntime {
    <#
    .SYNOPSIS
        One runtime's full text with its embedded block replaced or inserted.
    .DESCRIPTION
        The block goes after the file's leading comment header and before the
        first statement, so the kernel is defined by the time anything else in
        the file runs -- including a handler the runtime installs on load.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)][string]$Text,
        [Parameter(Mandatory)][string]$Block
    )

    $normal = $Text -replace "`r`n", "`n"
    $begin = $normal.IndexOf($BeginMarker)
    if ($begin -ge 0) {
        $end = $normal.IndexOf($EndMarker, $begin)
        if ($end -lt 0) { throw 'The runtime has an opening marker with no closing one; repair it by hand.' }
        $after = $end + $EndMarker.Length
        return $normal.Substring(0, $begin) + $Block + $normal.Substring($after)
    }

    # No block yet. Insert after the header comment -- whichever of the two
    # comment styles the runtime opens with -- so the copyright stays first.
    $insertAt = 0
    if ($normal.StartsWith('/*')) {
        $close = $normal.IndexOf('*/')
        if ($close -lt 0) { throw 'The runtime opens a block comment it never closes.' }
        $insertAt = $normal.IndexOf("`n", $close)
        $insertAt = if ($insertAt -lt 0) { $normal.Length } else { $insertAt + 1 }
    } else {
        $lines = $normal -split "`n"
        $offset = 0
        for ($i = 0; $i -lt $lines.Count; $i++) {
            $trimmed = $lines[$i].Trim()
            if ($trimmed -ne '' -and -not $trimmed.StartsWith('//')) { break }
            $offset += $lines[$i].Length + 1
        }
        $insertAt = $offset
    }
    return $normal.Substring(0, $insertAt) + "`n" + $Block + "`n" + $normal.Substring($insertAt)
}

function ConvertTo-GoQuoted {
    <#
    .SYNOPSIS
        A Go interpreted string literal for one value.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Value)
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"').Replace("`t", '\t').Replace("`r", '\r').Replace("`n", '\n')
    return '"' + $escaped + '"'
}

function Get-GoLocaleData {
    <#
    .SYNOPSIS
        The shared locale table as a Go source file.
    .DESCRIPTION
        Separators, plural rules, aliases and the supported set come from the
        locale manifest, the same file the PowerShell resolver and the browser
        kernel read. A runtime that consulted its own locale database instead
        would drift from the other two the next time that database shipped a
        change, and the drift shows up as one number written two ways on two
        surfaces describing the same run.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param()

    $manifest = ConvertFrom-Json -InputObject ([IO.File]::ReadAllText($ManifestPath))

    $supported = @()
    foreach ($p in $manifest.locales.PSObject.Properties) {
        if ($p.Value.status -eq 'supported') { $supported += $p.Name }
    }
    $supported = @($supported | Sort-Object)

    $sb = [Text.StringBuilder]::new()
    [void]$sb.AppendLine('// Generated by tools/Invoke-CatalogEmbed.ps1 from globalization/locale-manifest.json.')
    [void]$sb.AppendLine('// Edit the manifest and re-run that tool; changes made here are overwritten.')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('package i18n')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('// generatedLocaleData is every locale the manifest declares, including the')
    [void]$sb.AppendLine('// pseudo locales. Being present here does not make a locale selectable: only')
    [void]$sb.AppendLine('// generatedSupported decides that.')
    [void]$sb.AppendLine('var generatedLocaleData = map[string]LocaleData{')
    # Keys are padded to the widest so the emitted file is already gofmt-clean.
    # Generated Go that gofmt wants to rewrite is a lint failure nobody can fix
    # without editing a file whose header says not to.
    $localeNames = @($manifest.locales.PSObject.Properties.Name | Sort-Object)
    $keyWidth = 0
    foreach ($name in $localeNames) {
        $w = (ConvertTo-GoQuoted $name).Length + 1
        if ($w -gt $keyWidth) { $keyWidth = $w }
    }
    foreach ($name in $localeNames) {
        $locale = $manifest.locales.$name
        $nf = $locale.numberFormat
        $rule = if ($null -eq $locale.pluralRule) { '' } else { [string]$locale.pluralRule }
        $key = ((ConvertTo-GoQuoted $name) + ':').PadRight($keyWidth)
        [void]$sb.AppendLine(("`t{0} {{Group: {1}, Decimal: {2}, GroupSize: {3}, PluralRule: {4}, Direction: {5}}}," -f `
            $key, (ConvertTo-GoQuoted ([string]$nf.group)), (ConvertTo-GoQuoted ([string]$nf.decimal)),
            [int]$nf.groupSize, (ConvertTo-GoQuoted $rule), (ConvertTo-GoQuoted ([string]$locale.direction))))
    }
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('// generatedSupported is the set a request may actually resolve to. A locale')
    [void]$sb.AppendLine('// whose catalog is not reviewed is not in it, however complete its data looks.')
    [void]$sb.AppendLine('var generatedSupported = []string{')
    foreach ($name in $supported) { [void]$sb.AppendLine(("`t{0}," -f (ConvertTo-GoQuoted $name))) }
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('// generatedPseudo is the locales that exist only to make a translation')
    [void]$sb.AppendLine('// problem visible: expanded text that overflows a fixed box, and mirrored')
    [void]$sb.AppendLine('// text that exposes a hard-coded direction. They are never negotiable in a')
    [void]$sb.AppendLine('// release build -- a reader who received one would think the page was broken.')
    [void]$sb.AppendLine('var generatedPseudo = []string{')
    foreach ($p in ($manifest.locales.PSObject.Properties | Sort-Object Name)) {
        if ($p.Value.status -eq 'pseudo') { [void]$sb.AppendLine(("`t{0}," -f (ConvertTo-GoQuoted $p.Name))) }
    }
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('// generatedAliases maps a canonical tag the manifest does not ship to the one')
    [void]$sb.AppendLine('// it says answers for it. Keys are lowercased for lookup.')
    [void]$sb.AppendLine('var generatedAliases = map[string]string{')
    $aliasProps = @($manifest.aliases.PSObject.Properties | Sort-Object Name)
    $aliasWidth = 0
    foreach ($p in $aliasProps) {
        $w = (ConvertTo-GoQuoted $p.Name.ToLowerInvariant()).Length + 1
        if ($w -gt $aliasWidth) { $aliasWidth = $w }
    }
    foreach ($p in $aliasProps) {
        $key = ((ConvertTo-GoQuoted $p.Name.ToLowerInvariant()) + ':').PadRight($aliasWidth)
        [void]$sb.AppendLine(("`t{0} {1}," -f $key, (ConvertTo-GoQuoted ([string]$p.Value))))
    }
    [void]$sb.AppendLine('}')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine(("const generatedDefault = {0}" -f (ConvertTo-GoQuoted ([string]$manifest.default))))
    [void]$sb.AppendLine(("const generatedMaxTagLength = {0}" -f [int]$manifest.maxTagLength))
    [void]$sb.AppendLine(("const generatedMaxHeaderLength = {0}" -f [int]$manifest.maxHeaderLength))

    # Which compiled catalog set this binary was built against. Carried so a
    # message a reader complains about can be traced back to the artifacts that
    # rendered it, across a lab running two versions at once.
    $setPath = Join-Path $RepoRoot 'globalization/manifests/catalog-set.json'
    $setVersion = ''
    $setHash = ''
    if (Test-Path -LiteralPath $setPath -PathType Leaf) {
        $setBytes = [IO.File]::ReadAllBytes($setPath)
        $sha = [Security.Cryptography.SHA256]::Create()
        try { $setHash = [BitConverter]::ToString($sha.ComputeHash($setBytes)).Replace('-', '').ToLowerInvariant() }
        finally { $sha.Dispose() }
        $setVersion = [string](ConvertFrom-Json -InputObject ([Text.UTF8Encoding]::new($false).GetString($setBytes))).compilerVersion
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine(("const generatedCatalogVersion = {0}" -f (ConvertTo-GoQuoted $setVersion)))
    [void]$sb.AppendLine(("const generatedCatalogHash = {0}" -f (ConvertTo-GoQuoted $setHash)))
    return ($sb.ToString() -replace "`r`n", "`n")
}

function Get-GoCatalogFile {
    <#
    .SYNOPSIS
        One compiled catalog, re-homed into a service's own package.
    .DESCRIPTION
        The bytes are the compiler's; only the package clause changes, because
        the file has to compile inside the module that carries it. Taking the
        compiler's own output rather than re-encoding here is what makes "the
        service renders what the catalog says" a comparison instead of a claim.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][string]$SourcePath, [Parameter(Mandatory)][string]$PackageName)

    $text = ([IO.File]::ReadAllText($SourcePath)) -replace "`r`n", "`n"
    if ($text -notmatch '(?m)^package\s+\w+$') {
        throw "No package clause in $SourcePath; the compiler output is not what this expects."
    }
    return ($text -replace '(?m)^package\s+\w+$', "package $PackageName")
}

$findings = @()
$changed = @()

foreach ($target in $Targets) {
    $path = Join-Path $RepoRoot $target.Path
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $findings += "$($target.Path): no such runtime"
        continue
    }
    $block = Get-EmbeddedBlock -Domains $target.Domains -DomainsOnly:([bool]$target.DomainsOnly)
    $before = [IO.File]::ReadAllText($path)
    $after = Get-UpdatedRuntime -Text $before -Block $block

    if (($before -replace "`r`n", "`n") -ceq $after) {
        if (-not $Quiet) { Write-Output "$($target.Path): current" }
        continue
    }

    $changed += $target.Path
    if ($Check) {
        $findings += "$($target.Path): the embedded block does not match the kernel and the compiled catalog"
        continue
    }
    if ($PSCmdlet.ShouldProcess($target.Path, 'embed the catalog kernel and default-locale tables')) {
        [IO.File]::WriteAllText($path, $after)
        if (-not $Quiet) { Write-Output "$($target.Path): updated" }
    }
}

# --- The Go side: one shared locale table in the SDK, and the message data
# copied into each consuming module. A Go service cannot import across a module
# boundary it does not own, so distribution is the only way its data gets there.

function Set-GeneratedFile {
    <#
    .SYNOPSIS
        Write one generated file, or report that it is out of date.
    .OUTPUTS
        The relative path when it changed, or '' when it was already current.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([string])]
    param([Parameter(Mandatory)][string]$Relative, [Parameter(Mandatory)][string]$Text)

    $full = Join-Path $RepoRoot $Relative
    $existing = if (Test-Path -LiteralPath $full -PathType Leaf) {
        ([IO.File]::ReadAllText($full)) -replace "`r`n", "`n"
    } else { $null }

    if ($null -ne $existing -and $existing -ceq $Text) {
        # Status goes to the information stream, never to output: this function
        # RETURNS the path it changed, and a message written to the same stream
        # would come back as part of that value.
        if (-not $Quiet) { Write-Information "${Relative}: current" -InformationAction Continue }
        return ''
    }
    if ($Check) {
        $script:findings += "${Relative}: the generated file does not match the catalog sources"
        return $Relative
    }
    if ($PSCmdlet.ShouldProcess($Relative, 'write generated catalog data')) {
        $parent = Split-Path -Parent $full
        if (-not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
        [IO.File]::WriteAllText($full, $Text)
        if (-not $Quiet) { Write-Information "${Relative}: updated" -InformationAction Continue }
    }
    return $Relative
}

foreach ($browserTarget in $BrowserCatalogTargets) {
    $source = Join-Path $GeneratedBrowser $browserTarget.Source
    if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
        $findings += "$($browserTarget.Destination): no compiled browser artifact '$($browserTarget.Source)'. Run tools/Invoke-CatalogCompile.ps1 first."
        continue
    }
    $browserText = (([IO.File]::ReadAllText($source)) -replace "`r`n", "`n").TrimEnd() + "`n"
    $result = Set-GeneratedFile -Relative $browserTarget.Destination -Text $browserText
    if ($result) { $changed += $result }
}

$localeDataChange = Set-GeneratedFile -Relative $SdkLocaleData -Text (Get-GoLocaleData)
if ($localeDataChange) { $changed += $localeDataChange }

$adapterParts = @()
foreach ($part in @($FetchShimSource, $RawPageSource)) {
    $partPath = Join-Path $RepoRoot $part
    if (-not (Test-Path -LiteralPath $partPath -PathType Leaf)) {
        throw "The request adapter source is missing: $part"
    }
    $adapterParts += ('// From ' + $part + ' -- see that file for why.')
    $adapterParts += (Get-CodeAfterHeader -Text ([IO.File]::ReadAllText($partPath)))
}
$adapterJs = $adapterParts -join "`n"
foreach ($adapterTarget in $RequestAdapterTargets) {
    $moduleDir = Join-Path $RepoRoot $adapterTarget.Module
    if (-not (Test-Path -LiteralPath (Join-Path $moduleDir 'go.mod') -PathType Leaf)) {
        $findings += "$($adapterTarget.Module): no go.mod, so the request adapter has nowhere to land"
        continue
    }
    # A Go raw string takes every byte as written. The one byte it cannot hold
    # is the backtick that ends it, so that is spliced in as an interpreted
    # literal -- the adapter has none today, and this keeps that from becoming
    # a silent truncation if one is ever added.
    $quoted = $adapterJs.Replace('`', '` + "`" + `')
    $adapterSourceLabel = "$FetchShimSource and $RawPageSource"
    $goText = @"
// Generated by tools/Invoke-CatalogEmbed.ps1 from $adapterSourceLabel.
// Edit those sources and re-run the tool; changes made here are overwritten.

package $($adapterTarget.Package)

// requestAdapterScript is the ES5 stand-in this service's pages install before
// their own script. These pages are string literals and load no shared runtime,
// so the adapter every other page inherits has to travel with them.
const requestAdapterScript = ``$quoted``
"@
    $goText = ($goText -replace "`r`n", "`n").TrimEnd() + "`n"
    $relative = ($adapterTarget.Module + '/' + $adapterTarget.File) -replace '\\', '/'
    $result = Set-GeneratedFile -Relative $relative -Text $goText
    if ($result) { $changed += $result }
}

foreach ($goTarget in $GoTargets) {
    $moduleDir = Join-Path $RepoRoot $goTarget.Module
    if (-not (Test-Path -LiteralPath (Join-Path $moduleDir 'go.mod') -PathType Leaf)) {
        $findings += "$($goTarget.Module): no go.mod, so this is not a module the catalog can be copied into"
        continue
    }
    $packageName = Split-Path -Leaf $goTarget.Package
    foreach ($locale in ($goTarget.Locales | Sort-Object)) {
        foreach ($domain in ($goTarget.Domains | Sort-Object)) {
            $stem = ($locale -replace '[^A-Za-z0-9]', '') + "_$domain"
            $source = Join-Path $RepoRoot "globalization/generated/go/catalog/$stem.go"
            if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
                $findings += "$($goTarget.Module): no compiled Go artifact for '$locale.$domain'. Run tools/Invoke-CatalogCompile.ps1 first."
                continue
            }
            $relative = (Join-Path $goTarget.Module (Join-Path $goTarget.Package "$stem.go")) -replace '\\', '/'
            $result = Set-GeneratedFile -Relative $relative -Text (Get-GoCatalogFile -SourcePath $source -PackageName $packageName)
            if ($result) { $changed += $result }
        }
    }
}

# Both runtimes carry the same kernel. Comparing the written copies rather than
# trusting that both were written from one source is what catches a hand edit
# to the near copy, which is the way two copies of a file actually diverge.
$kernelText = ([IO.File]::ReadAllText($KernelPath)).TrimEnd() -replace "`r`n", "`n"
foreach ($target in $Targets) {
    $path = Join-Path $RepoRoot $target.Path
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { continue }
    $text = [IO.File]::ReadAllText($path) -replace "`r`n", "`n"
    if ($text.IndexOf($BeginMarker) -lt 0) {
        $findings += "$($target.Path): carries no embedded block"
        continue
    }
    # A domains-only target carries message tables and no kernel, because the
    # runtime its pages load first already defines one. Requiring a kernel here
    # would force the duplicate this mode exists to remove.
    if ($target.DomainsOnly) {
        if ($text.IndexOf($kernelText) -ge 0) {
            $findings += "$($target.Path): carries a second copy of the kernel its pages already load"
        }
        continue
    }
    if ($text.IndexOf($kernelText) -lt 0) {
        $findings += "$($target.Path): its copy of the kernel is not the one in globalization/kernel"
    }
}

if ($findings.Count -gt 0) {
    foreach ($f in $findings) { Write-Output "FINDING: $f" }
    Write-Output "Invoke-CatalogEmbed: $($findings.Count) finding(s)."
    exit 1
}

if (-not $Quiet) {
    $verb = if ($Check) { 'checked' } else { 'embedded into' }
    Write-Output "Invoke-CatalogEmbed: $verb $($Targets.Count) runtime(s), $($changed.Count) changed."
}
exit 0
