#!/usr/bin/env python3
# LICENSEURI https://yuruna.link/license
# Copyright (c) 2019-2026 by Alisson Sol et al.
"""Regenerate Ubuntu entrypoints and their shared-workflow integrity pins."""
import argparse
import hashlib
from pathlib import Path

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
for name in ('update', 'code', 'n8n', 'openclaw', 'postgresql'):
    body = root / f'guest/shared/ubuntu.{name}.sh'
    digest = hashlib.sha256(body.read_bytes()).hexdigest()
    text = f'''#!/bin/bash
# Version: 2026.09.30
# LICENSEURI https://yuruna.link/license
# Copyright (c) 2019-2026 by Alisson Sol et al.
# Generated by tools/Sync-GuestWorkflows.py; edit guest/shared/ubuntu.{name}.sh.
set -euo pipefail
workflow="guest/shared/ubuntu.{name}.sh"
expected="{digest}"
if [ -n "${{BASH_SOURCE[0]:-}}" ] && [ -f "${{BASH_SOURCE[0]}}" ]; then
    local_workflow="$(dirname "${{BASH_SOURCE[0]}}")/../shared/ubuntu.{name}.sh"
    if [ -f "$local_workflow" ]; then
        actual=$(sha256sum "$local_workflow")
        [ "${{actual%% *}}" = "$expected" ] || {{ echo "Shared workflow checksum mismatch" >&2; exit 3; }}
        exec bash "$local_workflow" "$@"
    fi
fi
# Reuse the installed fetcher's host discovery, pinned fallback, and digest gate.
export E_SHA="$expected" EXEC_SHA256="$expected" EXEC_REQUIRE_SHA256=1
exec /usr/local/lib/yuruna/fetch-and-execute.sh "$workflow" "$@"
'''
    for release in ('24', '26'):
        path = root / f'guest/ubuntu.server.{release}/ubuntu.server.{release}.{name}.sh'
        if args.check:
            if path.read_text() != text:
                raise SystemExit(f'Stale entrypoint: {path}')
        else:
            path.write_text(text)
