<#PSScriptInfo
.VERSION 2026.09.30
.GUID 42010094-0b04-4cef-9a6e-9de6dfe8624a
.AUTHOR Alisson Sol et al.
.COPYRIGHT (c) 2019-2026 by Alisson Sol et al.
.TAGS yuruna globalization diagnostics embed
.LICENSEURI https://yuruna.link/license
.PROJECTURI https://yuruna.com
.ICONURI
.EXTERNALMODULEDEPENDENCIES
.REQUIREDSCRIPTS
.EXTERNALSCRIPTDEPENDENCIES
.RELEASENOTES
.PRIVATEDATA
#>

#requires -version 7

<#
.SYNOPSIS
    Refresh the en-US message text embedded in automation/Get-SystemDiagnostic.ps1.
.DESCRIPTION
    Get-SystemDiagnostic.ps1 runs where no Yuruna module and no catalog can be
    loaded -- the console diagnostic rung downloads that one file into a guest's
    /tmp -- so it carries the compiled en-US entry of every message key it
    passes to Format-YurunaOperatorMessage. This tool rebuilds that copy from
    globalization/generated/powershell/en-US.<domain>.psd1 and writes it
    between the script's markers.

    The copy is gzip-compressed JSON in base64. Compression output can differ
    between .NET releases, so the comparison is made on the decoded entries:
    the file is rewritten only when the messages themselves differ, never
    because a new runtime compressed the same text into other bytes.

    Run it after changing a message the script prints, or after adding or
    removing a Format-YurunaOperatorMessage call in the script. Compile the
    catalogs first (tools/Invoke-CatalogCompile.ps1), because this reads their
    compiled output.

    Exit codes:
        0  the embedded copy is current, or was rewritten
        1  -Check found a stale copy
        2  the script or a catalog could not be read
.PARAMETER Check
    Report whether the embedded copy is current and exit 1 when it is not,
    without writing.
.PARAMETER Path
    The script to refresh. Defaults to automation/Get-SystemDiagnostic.ps1.
.PARAMETER CatalogRoot
    The compiled PowerShell catalog directory. Defaults to
    globalization/generated/powershell.
.PARAMETER Quiet
    Print only problems.
.EXAMPLE
    pwsh -NoProfile -File tools/Update-SystemDiagnosticText.ps1
.EXAMPLE
    pwsh -NoProfile -File tools/Update-SystemDiagnosticText.ps1 -Check
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [switch]$Check,
    [string]$Path,
    [string]$CatalogRoot,
    [switch]$Quiet
)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
if (-not $Path) { $Path = Join-Path $RepoRoot 'automation/Get-SystemDiagnostic.ps1' }
if (-not $CatalogRoot) { $CatalogRoot = Join-Path $RepoRoot 'globalization/generated/powershell' }

$BeginMarker = '# >>> embedded en-US messages -- generated by tools/Update-SystemDiagnosticText.ps1'
$EndMarker = '# <<< embedded en-US messages'
# Characters of base64 per source line. Short enough to read in a diff,
# long enough that the block stays a few hundred lines.
$ChunkLength = 96

function Get-DiagnosticMessageKey {
    <#
    .SYNOPSIS
        Every message key the script passes to Format-YurunaOperatorMessage.
    .DESCRIPTION
        A key that is not a literal cannot be embedded ahead of time, so it is
        an error rather than a gap the script would discover at run time.
    #>
    [CmdletBinding()]
    [OutputType([string[]])]
    param([Parameter(Mandatory)][System.Management.Automation.Language.Ast]$Ast)

    $keys = [System.Collections.Generic.SortedSet[string]]::new([StringComparer]::Ordinal)
    $calls = $Ast.FindAll({ param($node)
            $node -is [System.Management.Automation.Language.CommandAst] -and
            $node.GetCommandName() -eq 'Format-YurunaOperatorMessage'
        }, $true)
    foreach ($call in $calls) {
        $elements = $call.CommandElements
        for ($index = 1; $index -lt $elements.Count; $index++) {
            $element = $elements[$index]
            if ($element -isnot [System.Management.Automation.Language.CommandParameterAst] -or $element.ParameterName -ne 'Key') { continue }
            $value = if ($element.Argument) { $element.Argument } elseif ($index + 1 -lt $elements.Count) { $elements[$index + 1] } else { $null }
            if ($value -isnot [System.Management.Automation.Language.StringConstantExpressionAst]) {
                throw "Line $($call.Extent.StartLineNumber): Format-YurunaOperatorMessage needs a literal -Key for its text to be embedded."
            }
            [void]$keys.Add($value.Value)
        }
    }
    return [string[]]@($keys)
}

function Get-DesiredMessageTable {
    <#
    .SYNOPSIS
        The compiled en-US entry of each key, in ordinal key order.
    #>
    [CmdletBinding()]
    [OutputType([System.Collections.Specialized.OrderedDictionary])]
    param([Parameter(Mandatory)][AllowEmptyCollection()][string[]]$Key)

    $domains = @{}
    $table = [ordered]@{}
    foreach ($name in $Key) {
        $domain = $name.Split('.')[0]
        if (-not $domains.ContainsKey($domain)) {
            $catalog = Join-Path $CatalogRoot "en-US.$domain.psd1"
            if (-not (Test-Path -LiteralPath $catalog -PathType Leaf)) {
                throw "No compiled en-US catalog for domain '$domain' at $catalog. Run tools/Invoke-CatalogCompile.ps1 first."
            }
            $domains[$domain] = Import-PowerShellDataFile -LiteralPath $catalog -SkipLimitCheck
        }
        if (-not $domains[$domain].ContainsKey($name)) {
            throw "The compiled en-US catalog has no message '$name'. Add it to the catalog source and compile."
        }
        $table[$name] = $domains[$domain][$name]
    }
    return $table
}

function Get-OrdinalOrder {
    <#
    .SYNOPSIS
        Strings in ordinal order, independent of the host culture.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][AllowEmptyCollection()][string[]]$Value)

    $copy = [string[]]$Value.Clone()
    [Array]::Sort($copy, [StringComparer]::Ordinal)
    return $copy
}

function ConvertTo-SortedValue {
    <#
    .SYNOPSIS
        A copy of one entry with every dictionary's keys in ordinal order.
    #>
    [CmdletBinding()]
    [OutputType([System.Collections.Specialized.OrderedDictionary], [object[]], [object])]
    param([AllowNull()]$Item)

    if ($Item -is [System.Collections.IDictionary]) {
        $sorted = [ordered]@{}
        foreach ($name in (Get-OrdinalOrder -Value ([string[]]@($Item.Keys)))) {
            $sorted[$name] = ConvertTo-SortedValue -Item $Item[$name]
        }
        return $sorted
    }
    if ($Item -is [System.Collections.IList] -and $Item -isnot [string]) {
        return , @(foreach ($element in $Item) { ConvertTo-SortedValue -Item $element })
    }
    return $Item
}

function ConvertTo-CanonicalJson {
    <#
    .SYNOPSIS
        One entry as JSON with its dictionary keys in ordinal order.
    .DESCRIPTION
        A data file and a JSON document give back dictionaries whose key order
        need not agree. Sorting first makes two equal entries serialize to the
        same text, which is what the comparison needs.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([AllowNull()]$Value)

    return (ConvertTo-Json -InputObject (ConvertTo-SortedValue -Item $Value) -Depth 32 -Compress)
}

function ConvertTo-EmbeddedText {
    <#
    .SYNOPSIS
        The table as gzip-compressed JSON in base64.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][System.Collections.IDictionary]$Table)

    $json = ConvertTo-Json -InputObject $Table -Depth 32 -Compress
    $bytes = [Text.UTF8Encoding]::new($false).GetBytes($json)
    $buffer = [IO.MemoryStream]::new()
    try {
        $zip = [IO.Compression.GZipStream]::new($buffer, [IO.Compression.CompressionLevel]::SmallestSize, $true)
        try { $zip.Write($bytes, 0, $bytes.Length) } finally { $zip.Dispose() }
        return [Convert]::ToBase64String($buffer.ToArray())
    } finally { $buffer.Dispose() }
}

function ConvertFrom-EmbeddedText {
    <#
    .SYNOPSIS
        The table an embedded block holds, or $null when it cannot be decoded.
    #>
    [CmdletBinding()]
    [OutputType([hashtable])]
    param([Parameter(Mandatory)][AllowEmptyString()][string]$Text)

    try {
        $buffer = [IO.MemoryStream]::new([Convert]::FromBase64String($Text))
        $zip = [IO.Compression.GZipStream]::new($buffer, [IO.Compression.CompressionMode]::Decompress)
        $reader = [IO.StreamReader]::new($zip, [Text.UTF8Encoding]::new($false))
        try { return ($reader.ReadToEnd() | ConvertFrom-Json -AsHashtable) }
        finally { $reader.Dispose() }
    } catch {
        Write-Verbose "The embedded block could not be decoded: $($_.Exception.Message)"
        return $null
    }
}

function Get-EmbeddedBlock {
    <#
    .SYNOPSIS
        The marker lines and everything between them, located in the script.
    #>
    [CmdletBinding()]
    [OutputType([hashtable])]
    param([Parameter(Mandatory)][AllowEmptyString()][string[]]$Line)

    $begin = -1
    $end = -1
    for ($index = 0; $index -lt $Line.Count; $index++) {
        $trimmed = $Line[$index].Trim()
        if ($trimmed -ceq $BeginMarker) {
            if ($begin -ge 0) { throw 'The script opens the embedded block twice.' }
            $begin = $index
        } elseif ($trimmed -ceq $EndMarker) {
            if ($begin -lt 0 -or $end -ge 0) { throw 'The embedded block closes without opening, or closes twice.' }
            $end = $index
        }
    }
    if ($begin -lt 0 -or $end -lt 0) { throw "The script has no embedded block between '$BeginMarker' and '$EndMarker'." }
    $indent = $Line[$begin].Substring(0, $Line[$begin].Length - $Line[$begin].TrimStart().Length)
    $encoded = [Text.StringBuilder]::new()
    for ($index = $begin + 1; $index -lt $end; $index++) {
        $match = [regex]::Match($Line[$index], "^\s*'([A-Za-z0-9+/=]*)'\s*$")
        if (-not $match.Success) { throw "Line $($index + 1) of the embedded block is not a quoted base64 chunk." }
        [void]$encoded.Append($match.Groups[1].Value)
    }
    return @{ Begin = $begin; End = $end; Indent = $indent; Encoded = $encoded.ToString() }
}

try {
    $source = [IO.File]::ReadAllText($Path)
    $parseErrors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseInput($source, [ref]$null, [ref]$parseErrors)
    if ($parseErrors) { throw "The script does not parse: $($parseErrors[0].Message)" }
    $keys = Get-DiagnosticMessageKey -Ast $ast
    $desired = Get-DesiredMessageTable -Key $keys
    $lines = [string[]]($source -replace "`r`n", "`n" -split "`n")
    $block = Get-EmbeddedBlock -Line $lines
} catch {
    Write-Output "Update-SystemDiagnosticText: $($_.Exception.Message)"
    exit 2
}

# Compare entries, not bytes: see the description.
$embedded = ConvertFrom-EmbeddedText -Text $block.Encoded
$stale = [System.Collections.Generic.List[string]]::new()
if ($null -eq $embedded) {
    $stale.Add('(the block does not decode)')
} else {
    foreach ($name in $desired.Keys) {
        if (-not $embedded.ContainsKey($name)) { $stale.Add("missing $name"); continue }
        if ((ConvertTo-CanonicalJson -Value $embedded[$name]) -cne (ConvertTo-CanonicalJson -Value $desired[$name])) { $stale.Add("changed $name") }
    }
    foreach ($name in (Get-OrdinalOrder -Value ([string[]]@($embedded.Keys)))) {
        if (-not $desired.Contains($name)) { $stale.Add("unused $name") }
    }
}

$relative = [IO.Path]::GetRelativePath($RepoRoot, $Path) -replace '\\', '/'
if ($stale.Count -eq 0) {
    if (-not $Quiet) { Write-Output "Update-SystemDiagnosticText: ${relative}: current ($($desired.Count) messages)." }
    exit 0
}
if ($Check) {
    foreach ($entry in $stale) { Write-Output "STALE: $entry" }
    Write-Output "Update-SystemDiagnosticText: ${relative}: $($stale.Count) stale message(s). Run tools/Update-SystemDiagnosticText.ps1."
    exit 1
}

$encoded = ConvertTo-EmbeddedText -Table $desired
$updated = [System.Collections.Generic.List[string]]::new()
for ($index = 0; $index -le $block.Begin; $index++) { $updated.Add($lines[$index]) }
for ($offset = 0; $offset -lt $encoded.Length; $offset += $ChunkLength) {
    $updated.Add("$($block.Indent)'" + $encoded.Substring($offset, [Math]::Min($ChunkLength, $encoded.Length - $offset)) + "'")
}
for ($index = $block.End; $index -lt $lines.Count; $index++) { $updated.Add($lines[$index]) }
if ($PSCmdlet.ShouldProcess($relative, 'Rewrite the embedded en-US messages')) {
    [IO.File]::WriteAllText($Path, ($updated -join "`n"), [Text.UTF8Encoding]::new($false))
    if (-not $Quiet) {
        foreach ($entry in $stale) { Write-Output "UPDATED: $entry" }
        Write-Output "Update-SystemDiagnosticText: ${relative}: wrote $($desired.Count) messages."
    }
}
exit 0
