// Generated by tools/Invoke-CatalogCompile.ps1 from globalization/catalogs.
// Edit the source catalog and regenerate; changes made here are overwritten.
// locale: zh-CN  domain: aggregator

package catalog

// DatazhCNaggregator is the compiled catalog for this locale and domain. It is a
// string so the package carries no init cost until a caller decodes it.
const DatazhCNaggregator = `{
  "aggregator.announce_accepted_but_not_durably_recorded_retry": "通告已接受，但未持久化记录；请重试",
  "aggregator.announce_accepted_but_not_recorded": "通告已接受，但未记录",
  "aggregator.announce_disabled": "通告已禁用",
  "aggregator.announced_address_did_not_serve_status_json": "通告的地址未提供status.json",
  "aggregator.announced_address_serves_a_different_hostid": "通告的地址提供了不同的hostId",
  "aggregator.batch_mixes_multiple_hostids": "批次混用了多个hostIds",
  "aggregator.control_proof_verification_disabled_this_aggregator_holds_no_inte": "控制权证明验证已禁用：此聚合器未持有内部身份验证密钥",
  "aggregator.encode_failed": "编码失败",
  "aggregator.failed_to_encode_extension_hosts": "扩展宿主机编码失败",
  "aggregator.failed_to_encode_pool_status": "池状态编码失败",
  "aggregator.failed_to_encode_result": "结果编码失败",
  "aggregator.failed_to_encode_scrape_targets": "采集目标编码失败",
  "aggregator.failed_to_seal_the_token": "令牌封装失败",
  "aggregator.forget_host_disabled_no_auth_token_configured": "forget-host已禁用（未配置身份验证令牌）",
  "aggregator.help_address_to_listen_on_59add3f5": "监听地址",
  "aggregator.help_allow_pseudo": "启用诊断用伪区域设置",
  "aggregator.help_display_language": "显示语言：auto或受支持的区域设置",
  "aggregator.help_distinct_hosts_that_must_fail_within_cross_host_window_5475f083": "在-cross-host-window内触发池级事件所需的不同故障宿主机数量",
  "aggregator.help_drop_a_host_from_the_pool_view_this_long_after_last_co_58ed8eb1": "最后一次联系后经过此时长，将宿主机从池视图中移除；其每周期去重状态额外保留一小时，以免再次出现的宿主机被重复计数，且仪表板深层链接始终至少在24h内可解析。累计通过/失败（pass/fail）计数不会因此过期，请使用POST /api/v1/forget-host",
  "aggregator.help_file_holding_the_shared_bearer_token_that_gates_post_i_bd4b1952": "保存共享 Bearer 令牌的文件；POST /ingest、POST /api/v1/forget-host、POST /api/v1/handover-host 和 GET /api/v1/host-history 均需要此令牌。未指定文件、文件不存在或文件为空时，这些操作不可用（不会开放未经身份验证的控制路由）",
  "aggregator.help_loki_push_api_url_c89d9321": "Loki推送API URL",
  "aggregator.help_on_startup_restore_cycle_counts_from_loki_over_this_tr_36b6bc4f": "启动时，从Loki恢复此回溯窗口内的周期计数（0表示禁用）",
  "aggregator.help_open_an_incident_after_this_many_failed_cycles_within__fb192ccc": "在-incident-window内失败周期数达到此数量时，创建事件",
  "aggregator.help_poll_discover_interval_a9ec46cd": "轮询/发现（poll/discover）间隔",
  "aggregator.help_pool_name_label_31358a97": "池名称标签",
  "aggregator.help_port_the_machine_metrics_exporter_listens_on_for_each__0ae78ba6": "每台Windows宿主机上的machine-metrics导出器监听的端口，发布在/api/v1/prometheus-targets抓取文档中",
  "aggregator.help_reap_a_self_announced_extension_post_announce_not_refr_56b49fce": "清除在此窗口内未刷新的自行通告扩展（POST /announce）；0表示禁用通告路由",
  "aggregator.help_rotate_the_dashboard_lab_connection_token_this_often_0_f9f6d959": "按此间隔轮换仪表板的实验室连接令牌；0表示禁用实验室令牌磁贴和POST /api/v1/lab-token交换",
  "aggregator.help_squid_access_log_to_discover_pool_client_ips_from_93473aba": "用于发现池客户端IP的squid访问日志",
  "aggregator.help_status_service_port_to_probe_on_each_discovered_ip_e5073cc7": "在每个已发现IP上探测的status-service端口",
  "aggregator.help_the_pool_share_s_hosts_directory_on_this_machine_e_g_m_bd4bd40e": "池共享在本机上的hosts/目录（例如，e.g. /mnt/ypool-nas/hosts）；通过 /archive/<hostId>/test-cycles/... 提供已归档的周期结果，并允许 /go/cycle 解析这些结果。留空将禁用这两项功能，完全不注册该路由",
  "aggregator.help_tls_certificate_file_pem_when_both_tls_cert_and_tls_ke_643d7a8e": "TLS证书文件（PEM）；当-tls-cert和-tls-key均指定可读文件时，监听器使用HTTPS，否则使用明文HTTP",
  "aggregator.help_tls_private_key_file_pem_see_tls_cert_28be9018": "TLS私钥文件（PEM）；请参阅-tls-cert",
  "aggregator.help_trailing_window_for_the_n_failures_in_m_minutes_incide_60aa9aa2": "“M分钟内发生N次失败”事件规则的回溯窗口",
  "aggregator.help_window_for_cross_host_pool_wide_incident_correlation_b4663557": "跨宿主机（池级）事件关联窗口",
  "aggregator.host_not_known_to_the_pool": "池中无此宿主机记录",
  "aggregator.hostid_must_be_a_42_prefixed_32_hex_id": "hostId必须是以42开头的32位十六进制标识符",
  "aggregator.ingest_disabled": "数据摄取已禁用",
  "aggregator.invalid_hostid": "hostId无效",
  "aggregator.invalid_hostid_or_area": "hostId或area无效",
  "aggregator.invalid_statusport": "statusPort无效",
  "aggregator.invalid_target_address_detail": [
    "目标地址无效：",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.invalid_target_url": "目标URL无效",
  "aggregator.lab_token_exchange_disabled": "实验室令牌交换已禁用",
  "aggregator.labtoken_must_be_6_lowercase_letters_digits": "labToken必须由6个小写字母或数字（letters/digits）组成",
  "aggregator.log_archive_route_enabled_at_archive_from_value1_7b032a09": [
    "已在/archive/启用归档路由，来源为",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_auth_token_file_value1_unreadable_value2_ingest_contro_d458a79c": [
    "auth-token-file ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "不可读（",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "）；已禁用/ingest、控制证明和lab-token交换"
  ],
  "aggregator.log_extension_value1_refusing_value2_for_resolution_unansw_14b41da9": [
    "扩展",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "：拒绝使用",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "进行解析——已持续",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "未响应（",
    {
      "arg": "value4",
      "type": "detail",
      "trust": "external"
    },
    "）；该条目将保持抑制状态，直到服务重新通告或通告TTL到期将其清除"
  ],
  "aggregator.log_host_metrics_port_value1_is_not_a_valid_port_keeping_t_e686d724": [
    "host-metrics-port ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "不是有效端口；保留默认值",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_host_ttl_value1_is_not_positive_keeping_the_default_va_7ade3d03": [
    "host-ttl ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "不是正值；保留默认值",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_ingest_disabled_no_token_3a819fb4": "已禁用ingest（无令牌）",
  "aggregator.log_ingest_enabled_bearer_89578b00": "已启用ingest（持有者令牌）",
  "aggregator.log_internal_auth_key_read_from_value1_rebuild_this_proxy__c326800d": [
    "已从",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "读取内部身份验证密钥；请重新构建此代理，将密钥迁移到",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_lab_token_exchange_disabled_no_auth_token_configured_a47d49b1": "已禁用lab-token交换：未配置身份验证令牌",
  "aggregator.log_lab_token_exchange_off_4bdcc105": "，lab-token交换已关闭",
  "aggregator.log_lab_token_exchange_on_rotate_duration_5ce442f0": [
    "，lab-token交换已开启（轮换间隔",
    {
      "arg": "duration",
      "type": "detail",
      "trust": "external"
    },
    "）"
  ],
  "aggregator.log_lab_token_exchange_sealing_failed_value1_8aceabc2": [
    "lab-token交换：密封失败（",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "）"
  ],
  "aggregator.log_lab_token_exchange_value1_from_value2_3d2e9e4a": [
    "lab-token交换",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "，来源为",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_lab_token_rotation_failed_value1_keeping_previous_code_e2670350": [
    "lab-token轮换失败（",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "）；保留先前的代码"
  ],
  "aggregator.log_pool_aggregator_service_listening_on_value1_value2_poo_b30f8764": [
    "pool-aggregator-service正在监听",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "（",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "），pool=",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "，discover-from=",
    {
      "arg": "value4",
      "type": "detail",
      "trust": "external"
    },
    "，status-port=",
    {
      "arg": "value5",
      "type": "detail",
      "trust": "external"
    },
    "，loki=",
    {
      "arg": "value6",
      "type": "detail",
      "trust": "external"
    },
    "，interval=",
    {
      "arg": "value7",
      "type": "detail",
      "trust": "external"
    },
    "，",
    {
      "arg": "value8",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_rehydrate_announces_loki_query_value1_99a0159c": [
    "恢复通告：Loki查询：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_rehydrate_build_request_value1_11b6bf8a": [
    "rehydrate：构建请求：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_rehydrate_incidents_loki_query_value1_62f316f1": [
    "恢复事件：Loki查询：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_rehydrate_incidents_parse_value1_6c2aee5f": [
    "恢复事件：解析：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_rehydrate_loki_http_value1_value2_starting_with_empty__4f5aa860": [
    "恢复状态：Loki HTTP ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "：",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "（以空计数启动）"
  ],
  "aggregator.log_rehydrate_loki_query_value1_starting_with_empty_counts_13e1deb7": [
    "恢复状态：Loki查询：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "（以空计数启动）"
  ],
  "aggregator.log_rehydrate_parse_loki_response_value1_5d983c04": [
    "恢复状态：解析Loki响应：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_rehydrate_presence_loki_query_value1_5ba034a0": [
    "恢复在线状态：Loki查询：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_rehydrate_re_seeded_value1_host_s_from_the_presence_fe_b6c9e59f": [
    "恢复状态：已从在线状态数据流重新填充",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "台宿主机"
  ],
  "aggregator.log_rehydrate_re_seeded_value1_host_s_from_transition_base_4a5fd67e": [
    "恢复状态：已从状态转换记录的baseUrls重新填充",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "台宿主机（window=",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "）"
  ],
  "aggregator.log_rehydrate_restored_value1_open_incident_s_from_loki_9bcd828c": [
    "恢复状态：已从Loki恢复",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "个未关闭事件"
  ],
  "aggregator.log_rehydrate_restored_value1_self_announced_extension_s_f_e79d2b5f": [
    "恢复状态：已从Loki恢复",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "个自行通告的扩展"
  ],
  "aggregator.log_rehydrate_restored_value1_terminal_cycle_counts_from_l_de930fa3": [
    "恢复状态：已从Loki恢复",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "个终态周期计数（window=",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "）"
  ],
  "aggregator.log_rehydrate_warning_hit_the_5000_line_query_cap_counts_o_08375cc0": "恢复状态：警告，已达到5000行查询上限；早于最近5000次状态转换的计数可能偏低",
  "aggregator.log_squid_log_value1_value2_792a142a": [
    "squid日志",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "：",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_tls_cert_tls_key_set_but_not_both_readable_non_empty_s_f5dfa9e3": "已设置tls-cert/tls-key，但两者未同时满足可读且非空的条件；正在通过明文HTTP提供服务",
  "aggregator.log_value1_build_value2_cf7663df": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "构建：",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_value1_http_value2_eb0cd24f": [
    "诊断：",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " HTTP ",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.log_value1_value2_efae3eb9": [
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "：",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    }
  ],
  "aggregator.loki_query_failed": "loki查询失败",
  "aggregator.malformed_announce": "通告格式错误",
  "aggregator.malformed_request": "请求格式错误",
  "aggregator.method_not_allowed": "不允许使用此方法",
  "aggregator.metrics_are_served_to_this_host_only": "指标仅提供给此宿主机",
  "aggregator.missing_host": "缺少宿主机",
  "aggregator.no_cycle_results_folder_for_that_host_at_that_time": "该宿主机在该时间没有周期结果文件夹",
  "aggregator.no_live_host_for_that_extension_area": "该扩展区域没有在线宿主机",
  "aggregator.no_source_address": "无源地址",
  "aggregator.payload_too_large_or_unreadable": "载荷过大或无法读取",
  "aggregator.sender_identity_could_not_be_bound_undiscovered_ip_hostid_not_own": "无法绑定发送方身份（IP尚未发现、hostId不属于此IP或存在歧义）",
  "aggregator.stash_target_not_known_to_the_pool": "池中无此存储服务目标记录",
  "aggregator.target_host_must_be_the_announcing_address": "目标宿主机地址必须与发送通告的地址一致",
  "aggregator.the_pool_share_is_not_mounted_on_this_machine": "此计算机未挂载池共享",
  "aggregator.too_many_announced_extensions": "通告的扩展数量过多",
  "aggregator.too_many_failed_attempts_retry_later": "失败尝试次数过多；请稍后重试",
  "aggregator.too_many_lines": "行数过多",
  "aggregator.unauthorized": "未经授权",
  "aggregator.unknown_or_expired_lab_token": "实验室令牌未知或已过期",
  "aggregator.unsupported_range_use_1h_24h_7d_or_30d": "不支持此范围；请使用1h、24h、7d或30d",
  "aggregator.unusable_cycle_results_folder_for_that_host_at_that_time": "该宿主机在该时间的周期结果文件夹不可用"
}
`
