// Generated by tools/Invoke-CatalogCompile.ps1 from globalization/catalogs.
// Edit the source catalog and regenerate; changes made here are overwritten.
// locale: qps-Plocm  domain: download

package catalog

// DataqpsPlocmdownload is the compiled catalog for this locale and domain. It is a
// string so the package carries no init cost until a caller decodes it.
const DataqpsPlocmdownload = `{
  "download.actions": "[!‮Áçţíóñš‬ ~~~]",
  "download.actions_need_the_internal_authentication_key_as_a_bearer": "[!‮Áçţíóñš ñééď ţħé íñţéřñáļ áúţħéñţíçáţíóñ ķéý áš á ƀéářéř‬ ~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.api_arch_query_parameter_is_required_amd64_or_arm64": "[!‮ářçħ ʠúéřý ƥářáɱéţéř íš řéʠúířéď (áɱď64 óř ářɱ64)‬ ~~~~~~~~~~~~~~~~~~~~]",
  "download.api_detail": [
    "[!‮",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~]"
  ],
  "download.api_generation_not_found": "[!‮ğéñéřáţíóñ ñóţ ƒóúñď‬ ~~~~~~~~]",
  "download.api_invalid_generation_name": "[!‮íñṽáļíď ğéñéřáţíóñ ñáɱé‬ ~~~~~~~~~~]",
  "download.api_invalid_json_body_detail": [
    "[!‮íñṽáļíď ĴŠÓÑ ƀóďý: ",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~]"
  ],
  "download.api_no_image_store_configured": "[!‮ñó íɱáğé šţóřé çóñƒíğúřéď‬ ~~~~~~~~~~]",
  "download.api_pool_refresh_refused_reason": [
    "[!‮ƥóóļ řéƒřéšħ řéƒúšéď: ",
    {
      "arg": "reason",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~~]"
  ],
  "download.api_refresh_refused_reason": [
    "[!‮řéƒřéšħ řéƒúšéď: ",
    {
      "arg": "reason",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~]"
  ],
  "download.argv_value1": [
    "[!‮ářğṽ: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~]"
  ],
  "download.artifact": "[!‮Ářţíƒáçţ‬ ~~~~]",
  "download.as_of_value1": [
    "[!‮Áš óƒ ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~]"
  ],
  "download.as_of_value1_273588ee": [
    "[!‮áš óƒ ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~]"
  ],
  "download.attempt_arch": [
    "[!‮ářçħ ",
    {
      "arg": "value",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~]"
  ],
  "download.attempt_exit": [
    "[!‮éẋíţ ",
    {
      "arg": "value",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~]"
  ],
  "download.auto_seed": "[!‮Áúţó-šééď‬ ~~~~]",
  "download.available": "[!‮áṽáíļáƀļé‬ ~~~~]",
  "download.best_effort": "[!‮Ƀéšţ éƒƒóřţ‬ ~~~~~]",
  "download.best_effort_identity": [
    "[!‮",
    {
      "arg": "identity",
      "type": "detail",
      "trust": "external"
    },
    " - ƀéšţ éƒƒóřţ‬ ~~~~~~~~~~]"
  ],
  "download.byte_downloads_go_direct": "[!‮Ƀýţé ďóŵñļóáďš ğó ďířéçţ.‬ ~~~~~~~~~~]",
  "download.checksum": "[!‮Çħéçķšúɱ‬ ~~~~]",
  "download.command_line": "[!‮Çóɱɱáñď ļíñé‬ ~~~~~]",
  "download.configured": "[!‮çóñƒíğúřéď‬ ~~~~]",
  "download.deferred_count": [
    "[!‮Ďéƒéřřéď: ",
    {
      "arg": "count",
      "type": "integer",
      "trust": "internal"
    },
    ".‬ ~~~~~~~~]"
  ],
  "download.delete": "[!‮Ďéļéţé‬ ~~~]",
  "download.delete_every_generation_of_value1_value2_value3_value4_the_next_h": [
    "[!‮Ďéļéţé éṽéřý ğéñéřáţíóñ óƒ ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " (",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    ", ",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    ", ",
    {
      "arg": "value4",
      "type": "detail",
      "trust": "external"
    },
    ")?\n\nŢħé ñéẋţ ħóšţ řéʠúéšţ óř šééď ƥášš řé-ďóŵñļóáďš íţ ƒřóɱ óříğíñ. Ħóšţš ķééƥ ţħéíř ļóçáļ çóƥíéš.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]"
  ],
  "download.diagnostics": "[!‮Ďíáğñóšţíçš‬ ~~~~~]",
  "download.diagnostics_load_failed_value1": [
    "[!‮Ďíáğñóšţíçš ļóáď ƒáíļéď: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~~~~]"
  ],
  "download.diagnostics_yuruna_download_agent": "[!‮Ďíáğñóšţíçš — Ýúřúñá Ďóŵñļóáď Áğéñţ‬ ~~~~~~~~~~~~~~]",
  "download.discard_the_previous_generations_of_value1_value2_value3_value4_t": [
    "[!‮Ďíšçářď ţħé ƥřéṽíóúš ğéñéřáţíóñš óƒ ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " (",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    ", ",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    ", ",
    {
      "arg": "value4",
      "type": "detail",
      "trust": "external"
    },
    ")?\n\nŢħé çúřřéñţ ğéñéřáţíóñ íš ķéƥţ. Ţħé ďíšçářďéď óñéš ářé ñóţ řéçóṽéřáƀļé.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]"
  ],
  "download.download_pool": "[!‮Ďóŵñļóáď ƥóóļ‬ ~~~~~~]",
  "download.download_pool_yuruna_download_agent": "[!‮Ďóŵñļóáď ƥóóļ — Ýúřúñá Ďóŵñļóáď Áğéñţ‬ ~~~~~~~~~~~~~~~]",
  "download.enter_the_dashboard_lab_token_to_enable_actions": "[!‮Éñţéř ţħé ďášħƀóářď Ļáƀ ţóķéñ ţó éñáƀļé áçţíóñš‬ ~~~~~~~~~~~~~~~~~~~]",
  "download.entry": "[!‮Éñţřý‬ ~~]",
  "download.entry_bytes": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "one": [
        "[!‮",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " éñţřý - ",
        {
          "arg": "bytes",
          "type": "text",
          "trust": "internal"
        },
        " çúřřéñţ‬ ~~~~~~~~~~~~~]"
      ],
      "other": [
        "[!‮",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " éñţříéš - ",
        {
          "arg": "bytes",
          "type": "text",
          "trust": "internal"
        },
        " çúřřéñţ‬ ~~~~~~~~~~~~~~]"
      ]
    }
  },
  "download.entry_count": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "one": [
        "[!‮",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " éñţřý‬ ~~~~~~]"
      ],
      "other": [
        "[!‮",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " éñţříéš‬ ~~~~~~]"
      ]
    }
  },
  "download.error": "[!‮Éřřóř‬ ~~]",
  "download.every_value1": [
    "[!‮éṽéřý ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~]"
  ],
  "download.expired_value1_ago": [
    "[!‮éẋƥířéď ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " áğó‬ ~~~~~~~~]"
  ],
  "download.expires_in_value1": [
    "[!‮éẋƥířéš íñ ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~]"
  ],
  "download.failed": "[!‮ƒáíļéď‬ ~~~]",
  "download.fido_script": "[!‮Ƒíďó šçříƥţ‬ ~~~~~]",
  "download.force_refresh": "[!‮Ƒóřçé řéƒřéšħ‬ ~~~~~~]",
  "download.found": "[!‮ƒóúñď‬ ~~]",
  "download.freshness_window": [
    "[!‮Ƒřéšħñéšš: ",
    {
      "arg": "freshness",
      "type": "detail",
      "trust": "external"
    },
    "; ƥřéƒéţçħ ļéáď: ",
    {
      "arg": "lead",
      "type": "detail",
      "trust": "external"
    },
    ".‬ ~~~~~~~~~~~~~~~~~~~]"
  ],
  "download.guest": "[!‮Ğúéšţ‬ ~~]",
  "download.guide": "[!‮Ğúíďé‬ ~~]",
  "download.held_by_value1": [
    "[!‮ħéļď ƀý ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~]"
  ],
  "download.hosts_without_status": {
    "kind": "plural",
    "selector": "count",
    "variants": {
      "one": [
        "[!‮",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " ħóšţ ŵíţħóúţ šţáţúš.‬ ~~~~~~~~~~~~]"
      ],
      "other": [
        "[!‮",
        {
          "arg": "count",
          "type": "integer",
          "trust": "internal"
        },
        " ħóšţš ŵíţħóúţ šţáţúš.‬ ~~~~~~~~~~~~]"
      ]
    }
  },
  "download.image": "[!‮Íɱáğé‬ ~~]",
  "download.interpreter": "[!‮Íñţéřƥřéţéř‬ ~~~~~]",
  "download.interpreter_and_script_present_resolves_are_attempted": "[!‮Íñţéřƥřéţéř áñď šçříƥţ ƥřéšéñţ; řéšóļṽéš ářé áţţéɱƥţéď.‬ ~~~~~~~~~~~~~~~~~~~~~~]",
  "download.ips": "[!‮ÍƤš:‬ ~~]",
  "download.lab_token": "[!‮Ļáƀ ţóķéñ‬ ~~~~]",
  "download.last_pass_failed_value1": [
    "[!‮ļášţ ƥášš ƒáíļéď: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~]"
  ],
  "download.last_resolver_run": "[!‮Ļášţ řéšóļṽéř řúñ‬ ~~~~~~~]",
  "download.last_value1": [
    "[!‮ļášţ ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~]"
  ],
  "download.lease": "[!‮Ļéášé‬ ~~]",
  "download.loaded": "[!‮Ļóáďéď:‬ ~~~]",
  "download.manual_copy": "[!‮Çóƥý ţħé ďóŵñļóáďéď ƒíļé íñţó ţħé ďéšţíñáţíóñ ƒóļďéř.‬ ~~~~~~~~~~~~~~~~~~~~~~]",
  "download.manual_resolve": [
    "[!‮Ƒíďó ƒáíļéď. Ṽíšíţ ţħé ďóŵñļóáď ƥáğé áñď šéļéçţ: ",
    {
      "arg": "selections",
      "type": "detail",
      "trust": "external"
    },
    ".‬ ~~~~~~~~~~~~~~~~~~~~~~~~~]"
  ],
  "download.menu": "[!‮Ɱéñú‬ ~~]",
  "download.minted_url": [
    "[!‮Ɱíñţéď: ",
    {
      "arg": "url",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~]"
  ],
  "download.missing": "[!‮ɱíššíñğ‬ ~~~]",
  "download.next_scan": [
    "[!‮Ñéẋţ šçáñ: ",
    {
      "arg": "time",
      "type": "detail",
      "trust": "external"
    },
    ".‬ ~~~~~~~~]"
  ],
  "download.no_aggregator_url_and_no_internal_authentication_key_are_configur": [
    "[!‮Ñó áğğřéğáţóř ÚŘĻ áñď ñó íñţéřñáļ áúţħéñţíçáţíóñ ķéý ářé çóñƒíğúřéď, šó ţħé řéšóļṽéř ţéšţ íš ďíšáƀļéď. Šéţ ",
    {
      "arg": "command1",
      "type": "token",
      "trust": "internal"
    },
    " óř ",
    {
      "arg": "command2",
      "type": "token",
      "trust": "internal"
    },
    " óñ ţħé ďáéɱóñ ţó éñáƀļé íţ.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]"
  ],
  "download.no_aggregator_url_and_no_internal_authentication_key_are_configur_cb1dd86e": [
    "[!‮Ñó áğğřéğáţóř ÚŘĻ áñď ñó íñţéřñáļ áúţħéñţíçáţíóñ ķéý ářé çóñƒíğúřéď, šó Ƒóřçé řéƒřéšħ, Ďéļéţé áñď Ƥřúñé ářé ďíšáƀļéď. Šéţ ",
    {
      "arg": "command1",
      "type": "token",
      "trust": "internal"
    },
    " (ŵħíçħ ļéţš ţħé ďášħƀóářď'š Ļáƀ ţóķéñ úñļóçķ ţħéɱ) óř ",
    {
      "arg": "command2",
      "type": "token",
      "trust": "internal"
    },
    " óñ ţħé ďáéɱóñ ţó éñáƀļé ţħéɱ.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]"
  ],
  "download.no_aggregator_url_or_internal_authentication_key_configured_on_th": "[!‮Ñó áğğřéğáţóř ÚŘĻ óř íñţéřñáļ áúţħéñţíçáţíóñ ķéý çóñƒíğúřéď óñ ţħé ďáéɱóñ‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.no_pool_entries_yet_the_scanner_seeds_the_pool_on_its_next_pass_o": "[!‮Ñó ƥóóļ éñţříéš ýéţ. Ţħé šçáññéř šééďš ţħé ƥóóļ óñ íţš ñéẋţ ƥášš, óř úšé Ƒóřçé řéƒřéšħ óñ á řóŵ ţó šţářţ óñé ñóŵ.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.no_previous": "[!‮ñó ƥřéṽíóúš‬ ~~~~~]",
  "download.no_remembered_refresh_errors": "[!‮Ñó řéɱéɱƀéřéď řéƒřéšħ éřřóřš.‬ ~~~~~~~~~~~~]",
  "download.no_resolver": "[!‮ñó řéšóļṽéř‬ ~~~~~]",
  "download.no_resolver_run_recorded_since_the_daemon_started_a_scan_a_host_r": "[!‮Ñó řéšóļṽéř řúñ řéçóřďéď šíñçé ţħé ďáéɱóñ šţářţéď. Á šçáñ, á ħóšţ řéʠúéšţ, óř ţħé ţéšţ ƀúţţóñ áƀóṽé ŵíļļ řéçóřď óñé.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.none": "[!‮ñóñé‬ ~~]",
  "download.off": "[!‮óƒƒ‬ ~~]",
  "download.on": "[!‮óñ‬ ~]",
  "download.pages": "[!‮Ƥáğéš‬ ~~]",
  "download.pause": "[!‮Ƥáúšé‬ ~~]",
  "download.pool": "[!‮Ƥóóļ‬ ~~]",
  "download.pool_bytes": "[!‮Ƥóóļ ƀýţéš‬ ~~~~]",
  "download.previous_value1": [
    "[!‮ƥřéṽíóúš ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~]"
  ],
  "download.proxy": "[!‮Ƥřóẋý‬ ~~]",
  "download.prune_previous": "[!‮Ƥřúñé ƥřéṽíóúš‬ ~~~~~~]",
  "download.read_only": "[!‮řéáď-óñļý‬ ~~~~]",
  "download.recent_errors": "[!‮Řéçéñţ éřřóřš‬ ~~~~~~]",
  "download.recent_image_errors": "[!‮Řéçéñţ íɱáğé éřřóřš‬ ~~~~~~~~]",
  "download.refresh": "[!‮Řéƒřéšħ‬ ~~~]",
  "download.refresh_origin_probe": [
    "[!‮óříğíñ ƥřóƀé ",
    {
      "arg": "url",
      "type": "detail",
      "trust": "external"
    },
    ": ",
    {
      "arg": "detail",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~~]"
  ],
  "download.refresh_proxy_retry": [
    "[!‮ƥřóẋý šţřéáɱ ƒáíļéď (",
    {
      "arg": "proxy",
      "type": "detail",
      "trust": "external"
    },
    "); ďířéçţ řéţřý: ",
    {
      "arg": "direct",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~~~~~~~~~~~~]"
  ],
  "download.refresh_size_mismatch": [
    "[!‮óříğíñ ",
    {
      "arg": "url",
      "type": "detail",
      "trust": "external"
    },
    ": ĦÉÁĎ řéƥóřţéď ",
    {
      "arg": "expected",
      "type": "detail",
      "trust": "external"
    },
    " ƀýţé(š), ţħé ďóŵñļóáď ƥřóďúçéď ",
    {
      "arg": "actual",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]"
  ],
  "download.refresh_view": "[!‮Řéƒřéšħ ṽíéŵ‬ ~~~~~]",
  "download.resolve_failed_the_capture_below_says_why": "[!‮Řéšóļṽé ƒáíļéď -- ţħé çáƥţúřé ƀéļóŵ šáýš ŵħý.‬ ~~~~~~~~~~~~~~~~~~]",
  "download.resolve_succeeded_the_family_is_usable_on_this_agent": "[!‮Řéšóļṽé šúççééďéď -- ţħé ƒáɱíļý íš úšáƀļé óñ ţħíš áğéñţ.‬ ~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.resolved_variant": [
    "[!‮",
    {
      "arg": "identity",
      "type": "detail",
      "trust": "external"
    },
    " (řéšóļṽéď ",
    {
      "arg": "variant",
      "type": "detail",
      "trust": "external"
    },
    ")‬ ~~~~~~~~~~~~~]"
  ],
  "download.resolver_test": "[!‮Řéšóļṽéř ţéšţ‬ ~~~~~~]",
  "download.resolver_test_failed_to_run_value1": [
    "[!‮Řéšóļṽéř ţéšţ ƒáíļéď ţó řúñ: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~~~~~]"
  ],
  "download.resolver_test_refused_value1": [
    "[!‮Řéšóļṽéř ţéšţ řéƒúšéď: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~~~]"
  ],
  "download.retries_after": [
    "[!‮Řéţříéš áƒţéř ",
    {
      "arg": "time",
      "type": "detail",
      "trust": "external"
    },
    ".‬ ~~~~~~~~~]"
  ],
  "download.row_number": "[!‮Řóŵ ñúɱƀéř‬ ~~~~]",
  "download.running_a_resolve_can_take_up_to_3_minutes": "[!‮Řúññíñğ — á řéšóļṽé çáñ ţáķé úƥ ţó 3 ɱíñúţéš…‬ ~~~~~~~~~~~~~~~~~~]",
  "download.runs_the_vendored_fido_once_with_the_exact_parameters_a_resolve_u": "[!‮Řúñš ţħé ṽéñďóřéď Ƒíďó óñçé ŵíţħ ţħé éẋáçţ ƥářáɱéţéřš á řéšóļṽé úšéš.\n      Íţ ɱíñţš á šíğñéď ÚŘĻ áñď ďóŵñļóáďš ñóţħíñğ, ƀúţ éáçħ řúñ šƥéñďš á\n      Ɱíçřóšóƒţ šéššíóñ (ţħéíř šéřṽéřš řáţé-ƀáñ çħáţţý áďďřéššéš), šó úšé íţ ţó\n      ďíáğñóšé, ñóţ ţó ƥóļļ. Á šúççéššƒúļ ţéšţ çļéářš á řéɱéɱƀéřéď ƒáíļúřé óñ\n      ţħé šƥóţ; á ƒáíļéď óñé řé-ářɱš íţ.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.scanner": "[!‮Šçáññéř‬ ~~~]",
  "download.six_character_lab_token_from_the_dashboard": "[!‮Šíẋ-çħářáçţéř ļáƀ ţóķéñ ƒřóɱ ţħé ďášħƀóářď‬ ~~~~~~~~~~~~~~~~~]",
  "download.size_current_previous": "[!‮Šížé (çúřřéñţ / ƥřéṽíóúš)‬ ~~~~~~~~~~]",
  "download.skipped_value1": [
    "[!‮šķíƥƥéď: ",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~]"
  ],
  "download.source": "[!‮Šóúřçé‬ ~~~]",
  "download.standard_error": "[!‮Šţáñďářď éřřóř‬ ~~~~~~]",
  "download.standard_output": "[!‮Šţáñďářď óúţƥúţ‬ ~~~~~~]",
  "download.state": "[!‮Šţáţé‬ ~~]",
  "download.state_absent": "[!‮áƀšéñţ‬ ~~~]",
  "download.state_adopting": "[!‮áďóƥţíñğ‬ ~~~~]",
  "download.state_deleting": "[!‮ďéļéţíñğ‬ ~~~~]",
  "download.state_downloading": "[!‮ďóŵñļóáďíñğ‬ ~~~~~]",
  "download.state_failed": "[!‮ƒáíļéď‬ ~~~]",
  "download.state_fresh": "[!‮ƒřéšħ‬ ~~]",
  "download.state_match": "[!‮ɱáţçħ‬ ~~]",
  "download.state_mismatch": "[!‮ɱíšɱáţçħ‬ ~~~~]",
  "download.state_missing": "[!‮ɱíššíñğ‬ ~~~]",
  "download.state_probing": "[!‮ƥřóƀíñğ‬ ~~~]",
  "download.state_promoting": "[!‮ƥřóɱóţíñğ‬ ~~~~]",
  "download.state_ready": "[!‮řéáďý‬ ~~]",
  "download.state_resolving": "[!‮řéšóļṽíñğ‬ ~~~~]",
  "download.state_stale": "[!‮šţáļé‬ ~~]",
  "download.state_unavailable": "[!‮úñáṽáíļáƀļé‬ ~~~~~]",
  "download.state_unsupported": "[!‮úñšúƥƥóřţéď‬ ~~~~~]",
  "download.state_verifying": "[!‮ṽéříƒýíñğ‬ ~~~~]",
  "download.state_working": "[!‮ŵóřķíñğ‬ ~~~]",
  "download.stderr": "[!‮šţďéřř‬ ~~~]",
  "download.stdout": "[!‮šţďóúţ‬ ~~~]",
  "download.test_amd64_resolve": "[!‮Ţéšţ áɱď64 řéšóļṽé‬ ~~~~~~~~]",
  "download.test_arm64_resolve": "[!‮Ţéšţ ářɱ64 řéšóļṽé‬ ~~~~~~~~]",
  "download.the_6_character_code_on_the_yuruna_hosts_dashboard_s_lab_token_ti": "[!‮Ţħé 6-çħářáçţéř çóďé óñ ţħé Ýúřúñá ħóšţš ďášħƀóářď'š Ļáƀ ţóķéñ ţíļé; úƥƥéř óř ļóŵéř çášé ƀóţħ ŵóřķ. Ñééďéď óñļý ƒóř ţħé řéšóļṽéř ţéšţ ƀéļóŵ -- éṽéřýţħíñğ éļšé óñ ţħíš ƥáğé íš řéáď-óñļý.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.the_6_character_code_on_the_yuruna_hosts_dashboard_s_lab_token_ti_c3e28ca2": "[!‮Ţħé 6-çħářáçţéř çóďé óñ ţħé Ýúřúñá ħóšţš ďášħƀóářď'š Ļáƀ ţóķéñ ţíļé; úƥƥéř óř ļóŵéř çášé ƀóţħ ŵóřķ. Ţħé ƥóóļ áğğřéğáţóř çħéçķš íţ, áñď íţ řóţáţéš, šó á çóďé ñóţéď ďóŵñ ļášţ ŵééķ ŵíļļ ñóţ óƥéñ áñýţħíñğ.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.the_last_remembered_refresh_failure_per_pool_entry_newest_first_t": "[!‮Ţħé ļášţ řéɱéɱƀéřéď řéƒřéšħ ƒáíļúřé ƥéř ƥóóļ éñţřý, ñéŵéšţ ƒířšţ. Ţħéšé ářé ţħé éřřóřš ƀéħíñď á ƒáíļéď ƀáďğé óñ ţħé ƥóóļ ƥáğé.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.the_pool_share_is_not_available_the_agent_still_answers_metadata_": "[!‮Ţħé ƥóóļ šħářé íš ñóţ áṽáíļáƀļé. Ţħé áğéñţ šţíļļ áñšŵéřš ɱéţáďáţá, ƀúţ ñóţħíñğ çáñ ƀé ďóŵñļóáďéď óř šéřṽéď úñţíļ íţ íš ɱóúñţéď.‬ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~]",
  "download.this_folder": "[!‮ţħíš ƒóļďéř‬ ~~~~~]",
  "download.this_page": "[!‮ţħíš ƥáğé‬ ~~~~]",
  "download.totals": "[!‮Ţóţáļš‬ ~~~]",
  "download.unavailable": "[!‮úñáṽáíļáƀļé‬ ~~~~~]",
  "download.unlock_actions": "[!‮Úñļóçķ áçţíóñš‬ ~~~~~~]",
  "download.unlock_actions_first_enter_the_lab_token_above": "[!‮Úñļóçķ áçţíóñš ƒířšţ -- éñţéř ţħé Ļáƀ ţóķéñ áƀóṽé.‬ ~~~~~~~~~~~~~~~~~~~~]",
  "download.v": "[!‮ṽ‬ ~]",
  "download.value1_failed_for_value2_value3": [
    "[!‮",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " ƒáíļéď ƒóř ",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    ": ",
    {
      "arg": "value3",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~~~~~~]"
  ],
  "download.value1_failed_value2": [
    "[!‮",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " ƒáíļéď: ",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~]"
  ],
  "download.value1_of_value2_available": [
    "[!‮",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " óƒ ",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    " áṽáíļáƀļé‬ ~~~~~~~~~~~~]"
  ],
  "download.value1_on_the_share": [
    "[!‮",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " óñ ţħé šħářé‬ ~~~~~~~~~]"
  ],
  "download.value1_started": [
    "[!‮",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " šţářţéď.‬ ~~~~~~~]"
  ],
  "download.value1_started_value2": [
    "[!‮",
    {
      "arg": "value1",
      "type": "detail",
      "trust": "external"
    },
    " - šţářţéď ",
    {
      "arg": "value2",
      "type": "detail",
      "trust": "external"
    },
    "‬ ~~~~~~~~~~~]"
  ],
  "download.verified": "[!‮Ṽéříƒíéď‬ ~~~~]",
  "download.when": "[!‮Ŵħéñ‬ ~~]",
  "download.windows_11_family": "[!‮Ŵíñďóŵš 11 ƒáɱíļý‬ ~~~~~~~]",
  "download.writer": "[!‮ŵříţéř‬ ~~~]",
  "download.yuruna_download_agent": "[!‮Ýúřúñá Ďóŵñļóáď Áğéñţ‬ ~~~~~~~~~]"
}
`
